In [1]:
import pandas as pd
import pandas as pd
import glob
import os

def map_id(x):
    return str(x).lower().replace('.', '').replace(' ', '').replace(':', '').replace('-', '').replace('\xa0', '').replace(',', '').replace('+', '').replace('<sup>', '').replace('</sup>', '')


def get_df(s, path = 'data/'):
    li = []
    for filename in glob.glob(os.path.join(path , s + "*.csv")):
        print(filename)
        df = pd.read_csv(filename, index_col=None, header=0, encoding='utf-8')
        li.append(df)

    
    all_df = pd.concat(li, axis=0, ignore_index=True)
    all_df = all_df.drop_duplicates()
    all_df["citeid"] = all_df["Paper title"].apply(lambda x: map_id(x))
    all_df["citingid"] = all_df["Citing paper title"].apply(lambda x: map_id(x))
    return all_df

In [2]:
scholar = get_df('scholar')  # get the scholar citations
scholar

data\scholar-citations-1676383226.4907641.csv
data\scholar-citations-1676390245.6953535.csv
data\scholar-citations-1676633623.8536773.csv
data\scholar-citations.csv

,Paper title,Citing paper title,citeid,citingid
0,Crop management with the iot: An interdiscipli...,AgriFusion: An architecture for IoT and emergi...,cropmanagementwiththeiotaninterdisciplinarysurvey,agrifusionanarchitectureforiotandemergingtechn...
1,Crop management with the iot: An interdiscipli...,Everything you wanted to know about smart agri...,cropmanagementwiththeiotaninterdisciplinarysurvey,everythingyouwantedtoknowaboutsmartagriculture
2,Crop management with the iot: An interdiscipli...,Prediction of pest insect appearance using sen...,cropmanagementwiththeiotaninterdisciplinarysurvey,predictionofpestinsectappearanceusingsensorsan...
3,Crop management with the iot: An interdiscipli...,A smart and mechanized agricultural applicatio...,cropmanagementwiththeiotaninterdisciplinarysurvey,asmartandmechanizedagriculturalapplicationfrom...
4,Crop management with the iot: An interdiscipli...,Machine Learning in Precision Agriculture: A S...,cropmanagementwiththeiotaninterdisciplinarysurvey,machinelearninginprecisionagricultureasurveyon...
...,...,...,...,...
443,A-BI+: a framework for Augmented Business Inte...,Soluci�n de inteligencia de negocios para el a...,abiaframeworkforaugmentedbusinessintelligence,soluci�ndeinteligenciadenegociosparaelaprovech...
458,Social BI to understand the debate on vaccines...,Understanding public perceptions of COVID-19 c...,socialbitounderstandthedebateonvaccinesonthewe...,understandingpublicperceptionsofcovid19contact...
478,Making data platforms smarter with MOSES,Ecossistemas de big data: uma revis�o sistem�tica,makingdataplatformssmarterwithmoses,ecossistemasdebigdataumarevis�osistem�tica
504,Supporting the Generation of Data Narratives,Mod�liser la d�marche du data journaliste,supportingthegenerationofdatanarratives,mod�liserlad�marchedudatajournaliste
505,Supporting the Generation of Data Narratives,Un mod�le conceptual de narration de donn�es,supportingthegenerationofdatanarratives,unmod�leconceptualdenarrationdedonn�es

In [3]:
scopus = get_df('scopus')  # get the scopus citations
scopus

data\scopus-citations-1676384487.945707.csv
data\scopus-citations-1676384661.9739637.csv
data\scopus-citations-1676390158.4524183.csv
data\scopus-citations-1676633387.7854712.csv
data\scopus-citations.csv

,Paper title,Paper eid,Paper doi,Citing paper title,Citing paper eid,Citing paper doi,citeid,citingid
0,Enhancing Cubes with Models to Describe Multid...,2-s2.0-85107683405,10.1007/s10796-021-10147-3,Advances on Data Management and Information Sy...,2-s2.0-85125529748,10.1007/s10796-021-10235-4,enhancingcubeswithmodelstodescribemultidimensi...,advancesondatamanagementandinformationsystems
1,Enhancing Cubes with Models to Describe Multid...,2-s2.0-85107683405,10.1007/s10796-021-10147-3,Insight-Based Vocalization of OLAP Sessions,2-s2.0-85137993971,10.1007/978-3-031-15740-0_15,enhancingcubeswithmodelstodescribemultidimensi...,insightbasedvocalizationofolapsessions
2,Enhancing Cubes with Models to Describe Multid...,2-s2.0-85107683405,10.1007/s10796-021-10147-3,Describing Multidimensional Data Through Highl...,2-s2.0-85137469232,NaN,enhancingcubeswithmodelstodescribemultidimensi...,describingmultidimensionaldatathroughhighlight...
3,COOL: A framework for conversational OLAP,2-s2.0-85103428030,10.1016/j.is.2021.101752,HAMLET: A framework for Human-centered AutoML ...,2-s2.0-85145965157,10.1016/j.future.2022.12.035,coolaframeworkforconversationalolap,hamletaframeworkforhumancenteredautomlviastruc...
4,COOL: A framework for conversational OLAP,2-s2.0-85103428030,10.1016/j.is.2021.101752,Insight-Based Vocalization of OLAP Sessions,2-s2.0-85137993971,10.1007/978-3-031-15740-0_15,coolaframeworkforconversationalolap,insightbasedvocalizationofolapsessions
...,...,...,...,...,...,...,...,...
141,Cost-based Optimization of Multistore Query Plans,2-s2.0-85139405955,10.1007/s10796-022-10320-2,NaN,NaN,NaN,costbasedoptimizationofmultistorequeryplans,nan
142,Insight-Based Vocalization of OLAP Sessions,2-s2.0-85137993971,10.1007/978-3-031-15740-0_15,NaN,NaN,NaN,insightbasedvocalizationofolapsessions,nan
143,Describing Multidimensional Data Through Highl...,2-s2.0-85137469232,NaN,NaN,NaN,NaN,describingmultidimensionaldatathroughhighlight...,nan
146,Suggesting assess queries for interactive anal...,2-s2.0-85129353199,10.1109/TKDE.2022.3171516,NaN,NaN,NaN,suggestingassessqueriesforinteractiveanalysiso...,nan
153,Conversational OLAP,2-s2.0-85118769792,NaN,NaN,NaN,NaN,conversationalolap,nan

In [4]:
scopus_papers = scopus[["Paper title", "Paper eid", "Paper doi", "citeid"]].drop_duplicates().sort_values(by=["Paper title"]).reset_index(drop=True)
scopus_papers

,Paper title,Paper eid,Paper doi,citeid
0,A Similarity Function for Multi-Level and Mult...,2-s2.0-85051863772,NaN,asimilarityfunctionformultilevelandmultidimens...
1,A Survey and Experimental Study on Privacy-Pre...,2-s2.0-85132525373,10.1109/TKDE.2022.3174204,asurveyandexperimentalstudyonprivacypreserving...
2,A methodology for social BI,2-s2.0-84906819575,10.1145/2628194.2628250,amethodologyforsocialbi
3,A-BI<sup>+</sup>: A framework for Augmented Bu...,2-s2.0-85082441558,10.1016/j.is.2020.101520,abiaframeworkforaugmentedbusinessintelligence
4,Assess queries for interactive analysis of dat...,2-s2.0-85113712544,10.5441/002/edbt.2021.12,assessqueriesforinteractiveanalysisofdatacubes
5,Augmented business intelligence,2-s2.0-85062645475,NaN,augmentedbusinessintelligence
6,COOL: A framework for conversational OLAP,2-s2.0-85103428030,10.1016/j.is.2021.101752,coolaframeworkforconversationalolap
7,Conversational OLAP,2-s2.0-85118769792,NaN,conversationalolap
8,Conversational OLAP in action,2-s2.0-85113716450,10.5441/002/edbt.2021.74,conversationalolapinaction
9,Cost-based Optimization of Multistore Query Plans,2-s2.0-85139405955,10.1007/s10796-022-10320-2,costbasedoptimizationofmultistorequeryplans
10,Crop Management with the IoT: An Interdiscipli...,2-s2.0-85100942957,10.3390/agronomy11010181,cropmanagementwiththeiotaninterdisciplinarysurvey
11,DART: De-Anonymization of personal gazetteers ...,2-s2.0-85093926143,10.1016/j.jisa.2020.102634,dartdeanonymizationofpersonalgazetteersthrough...
12,Describing Multidimensional Data Through Highl...,2-s2.0-85137469232,NaN,describingmultidimensionaldatathroughhighlight...
13,Enhancing Cubes with Models to Describe Multid...,2-s2.0-85107683405,10.1007/s10796-021-10147-3,enhancingcubeswithmodelstodescribemultidimensi...
14,HAMLET: A framework for Human-centered AutoML ...,2-s2.0-85145965157,10.1016/j.future.2022.12.035,hamletaframeworkforhumancenteredautomlviastruc...
15,Insight-Based Vocalization of OLAP Sessions,2-s2.0-85137993971,10.1007/978-3-031-15740-0_15,insightbasedvocalizationofolapsessions
16,Making data platforms smarter with MOSES,2-s2.0-85109035166,10.1016/j.future.2021.06.031,makingdataplatformssmarterwithmoses
17,Map-matching on big data: A distributed and ef...,2-s2.0-85070329171,10.23919/MIPRO.2019.8757119,mapmatchingonbigdataadistributedandefficiental...
18,Multi-sensor profiling for precision soil-mois...,2-s2.0-85129541562,10.1016/j.compag.2022.106924,multisensorprofilingforprecisionsoilmoisturemo...
19,OLAP Querying of Document Stores in the Presen...,2-s2.0-85090883258,NaN,olapqueryingofdocumentstoresinthepresenceofsch...
20,Optimizing Execution Plans in a Multistore,2-s2.0-85115134032,10.1007/978-3-030-82472-3_11,optimizingexecutionplansinamultistore
21,Social BI to understand the debate on vaccines...,2-s2.0-85070525370,10.1007/s13278-019-0590-x,socialbitounderstandthedebateonvaccinesonthewe...
22,Social business intelligence in action,2-s2.0-84976641685,10.1007/978-3-319-39696-53,socialbusinessintelligenceinaction
23,Suggesting assess queries for interactive anal...,2-s2.0-85129353199,10.1109/TKDE.2022.3171516,suggestingassessqueriesforinteractiveanalysiso...
24,Summarization and visualization of multi-level...,2-s2.0-85079239065,10.1016/j.ins.2020.02.006,summarizationandvisualizationofmultilevelandmu...
25,Supporting the generation of data narratives,2-s2.0-85095734112,NaN,supportingthegenerationofdatanarratives
26,The Tell-Tale Cube,2-s2.0-85090100247,10.1007/978-3-030-54832-2_16,thetelltalecube
27,Towards a Conceptual Model for Data Narratives,2-s2.0-85097380415,10.1007/978-3-030-62522-1_19,towardsaconceptualmodelfordatanarratives
28,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,towardsafoundationalapiforresilientdistributed...
29,Towards conversational OLAP,2-s2.0-85082444588,NaN,towardsconversationalolap
30,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,trajectorybasedspatiotemporalentitylinking

In [5]:
scopus_lookup = {}
for x in scopus_papers.to_numpy():
    scopus_lookup[x[3]] = x[:3]

In [6]:
scopus_unique = scopus["citeid"].sort_values().unique()
scopus_unique

array(['abiaframeworkforaugmentedbusinessintelligence',
       'amethodologyforsocialbi',
       'asimilarityfunctionformultilevelandmultidimensionalitemsets',
       'assessqueriesforinteractiveanalysisofdatacubes',
       'asurveyandexperimentalstudyonprivacypreservingtrajectorydatapublishing',
       'augmentedbusinessintelligence', 'conversationalolap',
       'conversationalolapinaction',
       'coolaframeworkforconversationalolap',
       'costbasedoptimizationofmultistorequeryplans',
       'cropmanagementwiththeiotaninterdisciplinarysurvey',
       'dartdeanonymizationofpersonalgazetteersthroughsocialtrajectories',
       'describingmultidimensionaldatathroughhighlights(discussionpaper)',
       'enhancingcubeswithmodelstodescribemultidimensionaldata',
       'hamletaframeworkforhumancenteredautomlviastructuredargumentation',
       'insightbasedvocalizationofolapsessions',
       'makingdataplatformssmarterwithmoses',
       'mapmatchingonbigdataadistributedandefficientalgorithmwithahiddenmarkovmodel',
       'multisensorprofilingforprecisionsoilmoisturemonitoring',
       'olapqueryingofdocumentstoresinthepresenceofschemavariety',
       'optimizingexecutionplansinamultistore',
       'socialbitounderstandthedebateonvaccinesonthewebandsocialmediaunravelingtheantifreeandprovaxcommunitiesinitaly',
       'socialbusinessintelligenceinaction',
       'suggestingassessqueriesforinteractiveanalysisofmultidimensionaldata',
       'summarizationandvisualizationofmultilevelandmultidimensionalitemsets',
       'supportingthegenerationofdatanarratives', 'thetelltalecube',
       'towardsaconceptualmodelfordatanarratives',
       'towardsafoundationalapiforresilientdistributedsystemsdesign',
       'towardsconversationalolap',
       'trajectorybasedspatiotemporalentitylinking'], dtype=object)

In [7]:
scholar_unique = scholar["citeid"].sort_values().unique()
scholar_unique

array(['abiaframeworkforaugmentedbusinessintelligence',
       'asimilarityfunctionformultilevelandmultidimensionalitemsets',
       'assessqueriesforinteractiveanalysisofdatacubes',
       'asurveyandexperimentalstudyonprivacypreservingtrajectorydatapublishing',
       'augmentedbusinessintelligence', 'conversationalolapinaction',
       'coolaframeworkforconversationalolap',
       'costbasedoptimizationofmultistorequeryplans',
       'cropmanagementwiththeiotaninterdisciplinarysurvey',
       'dartdeanonymizationofpersonalgazetteersthroughsocialtrajectories',
       'enhancingcubeswithmodelstodescribemultidimensionaldata',
       'makingdataplatformssmarterwithmoses',
       'mapmatchingonbigdataadistributedandefficientalgorithmwithahiddenmarkovmodel',
       'olapqueryingofdocumentstoresinthepresenceofschemavariety',
       'optimizingexecutionplansinamultistore',
       'socialbitounderstandthedebateonvaccinesonthewebandsocialmediaunravelingtheantifreeandprovaxcommunitiesinitaly',
       'summarizationandvisualizationofmultilevelandmultidimensionalitemsets',
       'supportingthegenerationofdatanarratives', 'thetelltalecube',
       'towardsaconceptualmodelfordatanarratives',
       'towardsafoundationalapiforresilientdistributedsystemsdesign',
       'towardsconversationalolap',
       'trajectorybasedspatiotemporalentitylinking'], dtype=object)

In [8]:
not_cited_ids = []
for x in scholar_unique:  # for each paper in scholar
    citations_scholar = scholar[scholar["citeid"] == x]  # get its citing papers from scholar
    paper_scopus = scopus[(scopus["citeid"] == x)]  # get the paper from scopus...
    if len(paper_scopus) == 0:  # if the paper is not on scopus...
        print(x + " is not in scopus")
    else:
        for y in citations_scholar["citingid"].unique():  # for each of the citing papers from scholar
            if len(paper_scopus[(scopus["citingid"] == y)]) == 0:  # if this citation is not in scopus...
                not_cited_ids.append([x, y])  # add it
not_cited = pd.DataFrame(not_cited_ids, columns=["citeid", "citingid"])
not_cited

C:\Users\matteo.francia5\AppData\Local\Temp\ipykernel_12892\698780769.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if len(paper_scopus[(scopus["citingid"] == y)]) == 0:  # if this citation is not in scopus...

,citeid,citingid
0,abiaframeworkforaugmentedbusinessintelligence,lainteligenciadenegociosylaanalíticadedatosenl...
1,abiaframeworkforaugmentedbusinessintelligence,suggestingassessqueriesforinteractiveanalysiso...
2,abiaframeworkforaugmentedbusinessintelligence,theimpactofbusinessintelligencecharacteristics...
3,abiaframeworkforaugmentedbusinessintelligence,augmentingtheknowledgepyramidwithunconventiona...
4,abiaframeworkforaugmentedbusinessintelligence,lainteligenciadenegociosylaanalíticadedatosenl...
...,...,...
99,trajectorybasedspatiotemporalentitylinking,frequencybasedrandomizationforguaranteeingdiff...
100,trajectorybasedspatiotemporalentitylinking,spatialdataqualityintheioteramanagementandexpl...
101,trajectorybasedspatiotemporalentitylinking,informationresiliencethenexusofresponsibleanda...
102,trajectorybasedspatiotemporalentitylinking,anefficientapproachforspatialtrajectoryanonymi...
103,trajectorybasedspatiotemporalentitylinking,augmentingtheknowledgepyramidwithunconventiona...

In [9]:
missing_papers = scholar[["Citing paper title", "citingid"]].drop_duplicates().merge(not_cited, on=["citingid"])
missing_papers

,Citing paper title,citingid,citeid
0,Everything you wanted to know about smart agri...,everythingyouwantedtoknowaboutsmartagriculture,cropmanagementwiththeiotaninterdisciplinarysurvey
1,Analysis of chlorophyll and carotenoids conten...,analysisofchlorophyllandcarotenoidscontentinbr...,cropmanagementwiththeiotaninterdisciplinarysurvey
2,LambdAgrIoT: a new architecture for agricultur...,lambdagriotanewarchitectureforagriculturalauto...,cropmanagementwiththeiotaninterdisciplinarysurvey
3,An Intelligent Agro-Cloud Framework For Effici...,anintelligentagrocloudframeworkforefficientcro...,cropmanagementwiththeiotaninterdisciplinarysurvey
4,A model for automatized data integration in ha...,amodelforautomatizeddataintegrationinhadoopbas...,cropmanagementwiththeiotaninterdisciplinarysurvey
...,...,...,...
99,The Impact of Business Intelligence Characteri...,theimpactofbusinessintelligencecharacteristics...,abiaframeworkforaugmentedbusinessintelligence
100,La inteligencia de negocios y la anal�tica de ...,lainteligenciadenegociosylaanal�ticadedatosenl...,abiaframeworkforaugmentedbusinessintelligence
101,Soluci�n de inteligencia de negocios para el a...,soluci�ndeinteligenciadenegociosparaelaprovech...,abiaframeworkforaugmentedbusinessintelligence
102,Understanding public perceptions of COVID-19 c...,understandingpublicperceptionsofcovid19contact...,socialbitounderstandthedebateonvaccinesonthewe...
103,Ecossistemas de big data: uma revis�o sistem�tica,ecossistemasdebigdataumarevis�osistem�tica,makingdataplatformssmarterwithmoses

In [10]:
scopus_acc = []
not_in_scopus = []
missin_papers_scopus = pd.DataFrame(scopus_acc, columns=["Citing paper title", "Citing paper eid", "Citing paper doi", "citingid"]).drop_duplicates()

In [11]:
import pybliometrics
from pybliometrics.scopus import ScopusSearch
from pybliometrics.scopus.utils import config
from pybliometrics.scopus import AuthorRetrieval
import sys
import pandas as pd
import time

for x in missing_papers[["Citing paper title", "citingid"]].drop_duplicates().to_numpy():  # [["making data platform smarter with moses"]]:
    string = "TITLE-ABS-KEY({})".format(' AND '.join(x[0].lower().split(' ')))
    try:
        s = ScopusSearch(string)
        if s.results is not None and len(s.results) > 0:
            papers = [[y.title, y.eid, y.doi, x[1]] for y in s.results]
            for paper in papers:
                scopus_acc = scopus_acc + [paper]
                missin_papers_scopus = pd.DataFrame(scopus_acc, columns=["Citing paper title", "Citing paper eid", "Citing paper doi", "citingid"]).drop_duplicates()
        else:
            not_in_scopus = not_in_scopus + [x[0]]
        time.sleep(1)
    except Exception as e:
        print(x[0] + " " + string + ": " + str(e))

Analysis of chlorophyll and carotenoids content in brassica chinensis plants using IoT-based sprinkle irrigation TITLE-ABS-KEY(analysis AND of AND chlorophyll AND and AND carotenoids AND content AND in AND brassica AND chinensis AND plants AND using AND iot-based AND sprinkle AND irrigation): Error translating query
Augmenting the Knowledge Pyramid with Unconventional Data and Advanced Analytics TITLE-ABS-KEY(augmenting AND the AND knowledge AND pyramid AND with AND unconventional AND data AND and AND advanced AND analytics): Error translating query
Distributed Applications and Interoperable Systems TITLE-ABS-KEY(distributed AND applications AND and AND interoperable AND systems): Error translating query
Distributed and Decentralized Algorithms for Functional Programmable Matter TITLE-ABS-KEY(distributed AND and AND decentralized AND algorithms AND for AND functional AND programmable AND matter): Error translating query
Narrative Visualizations Best Practices and Evaluation: A Systematic Mapping Study TITLE-ABS-KEY(narrative AND visualizations AND best AND practices AND and AND evaluation: AND a AND systematic AND mapping AND study): Error translating query
The Impact of Business Intelligence Characteristics on Competitiveness of Companies with the Mediating Role of Entrepreneurship, Market Orientation and Business … TITLE-ABS-KEY(the AND impact AND of AND business AND intelligence AND characteristics AND on AND competitiveness AND of AND companies AND with AND the AND mediating AND role AND of AND entrepreneurship, AND market AND orientation AND and AND business AND …): Error translating query
La inteligencia de negocios y la analítica de datos en los procesos empresariales Business intelligence and data analytics in business processes TITLE-ABS-KEY(la AND inteligencia AND de AND negocios AND y AND la AND analítica AND de AND datos AND en AND los AND procesos AND empresariales AND business AND intelligence AND and AND data AND analytics AND in AND business AND processes): Error translating query
Conceptualizing Analytics: An Overview of Business Intelligence and Analytics from a Conceptual-Modeling Perspective TITLE-ABS-KEY(conceptualizing AND analytics: AND an AND overview AND of AND business AND intelligence AND and AND analytics AND from AND a AND conceptual-modeling AND perspective): Error translating query
Concepts towards an automated data pre-processing and preparation within data lakes TITLE-ABS-KEY(concepts AND towards AND an AND automated AND data AND pre-processing AND and AND preparation AND within AND data AND lakes): Error translating query
Spatial data quality in the Internet of Things: Management, exploitation, and prospects TITLE-ABS-KEY(spatial AND data AND quality AND in AND the AND internet AND of AND things: AND management, AND exploitation, AND and AND prospects): Error translating query
A survey and experimental study on privacy-preserving trajectory data publishing TITLE-ABS-KEY(a AND survey AND and AND experimental AND study AND on AND privacy-preserving AND trajectory AND data AND publishing): Error translating query
Spatial Data Quality in the IoT Era: Management and Exploitation TITLE-ABS-KEY(spatial AND data AND quality AND in AND the AND iot AND era: AND management AND and AND exploitation): Error translating query
Information Resilience: the nexus of responsible and agile approaches to information use TITLE-ABS-KEY(information AND resilience: AND the AND nexus AND of AND responsible AND and AND agile AND approaches AND to AND information AND use): Error translating query
SeRViz: an interactive visualization framework for the analysis of sequential rules and frequent itemsets TITLE-ABS-KEY(serviz: AND an AND interactive AND visualization AND framework AND for AND the AND analysis AND of AND sequential AND rules AND and AND frequent AND itemsets): Error translating query
Serviz: A Visual Analytics System for the Analysis of Sequential Rules and its Application to Airport Ground Handling Operations TITLE-ABS-KEY(serviz: AND a AND visual AND analytics AND system AND for AND the AND analysis AND of AND sequential AND rules AND and AND its AND application AND to AND airport AND ground AND handling AND operations): Error translating query
Towards Privacy Preservation using Clustering based Anonymization: Recent Advances and Future Research Outlook TITLE-ABS-KEY(towards AND privacy AND preservation AND using AND clustering AND based AND anonymization: AND recent AND advances AND and AND future AND research AND outlook): Error translating query
Fouille de s�quences de mobilit� s�mantique: sur l'�laboration de mesures pour la comparaison, l'analyse et la d�couverte de comportements TITLE-ABS-KEY(fouille AND de AND s�quences AND de AND mobilit� AND s�mantique: AND sur AND l'�laboration AND de AND mesures AND pour AND la AND comparaison, AND l'analyse AND et AND la AND d�couverte AND de AND comportements): Error translating query
Mod�liser la d�marche du data journaliste TITLE-ABS-KEY(mod�liser AND la AND d�marche AND du AND data AND journaliste): Error translating query
Un mod�le conceptual de narration de donn�es TITLE-ABS-KEY(un AND mod�le AND conceptual AND de AND narration AND de AND donn�es): Error translating query
La inteligencia de negocios y la anal�tica de datos en los procesos empresariales TITLE-ABS-KEY(la AND inteligencia AND de AND negocios AND y AND la AND anal�tica AND de AND datos AND en AND los AND procesos AND empresariales): Error translating query
The Impact of Business Intelligence Characteristics on Competitiveness of Companies with the Mediating Role of Entrepreneurship, Market Orientation and Business � TITLE-ABS-KEY(the AND impact AND of AND business AND intelligence AND characteristics AND on AND competitiveness AND of AND companies AND with AND the AND mediating AND role AND of AND entrepreneurship, AND market AND orientation AND and AND business AND �): Error translating query
La inteligencia de negocios y la anal�tica de datos en los procesos empresariales Business intelligence and data analytics in business processes TITLE-ABS-KEY(la AND inteligencia AND de AND negocios AND y AND la AND anal�tica AND de AND datos AND en AND los AND procesos AND empresariales AND business AND intelligence AND and AND data AND analytics AND in AND business AND processes): Error translating query
Soluci�n de inteligencia de negocios para el aprovechamiento de los datos del servicio m�dico en una entidad bancaria TITLE-ABS-KEY(soluci�n AND de AND inteligencia AND de AND negocios AND para AND el AND aprovechamiento AND de AND los AND datos AND del AND servicio AND m�dico AND en AND una AND entidad AND bancaria): Error translating query
Understanding public perceptions of COVID-19 contact tracing apps: Artificial intelligence�enabled social media analysis TITLE-ABS-KEY(understanding AND public AND perceptions AND of AND covid-19 AND contact AND tracing AND apps: AND artificial AND intelligence�enabled AND social AND media AND analysis): Error translating query
Ecossistemas de big data: uma revis�o sistem�tica TITLE-ABS-KEY(ecossistemas AND de AND big AND data: AND uma AND revis�o AND sistem�tica): Error translating query

In [12]:
missin_papers_scopus

,Citing paper title,Citing paper eid,Citing paper doi,citingid
0,LambdAgrIoT: a new architecture for agricultur...,2-s2.0-85140242438,10.1007/s10586-022-03592-5,lambdagriotanewarchitectureforagriculturalauto...
1,Applications of IoT for optimized greenhouse e...,2-s2.0-85129326292,10.1016/j.compag.2022.106993,thingsforsmartagricultureindevelopingcountries
2,Learning Space-Time Crop Yield Patterns with Z...,2-s2.0-85143575925,None,thingsforsmartagricultureindevelopingcountries
3,IOT based solar powered smart irrigation system,2-s2.0-85131869537,10.1063/5.0081783,thingsforsmartagricultureindevelopingcountries
4,Utilization of Internet of Things and Wireless...,2-s2.0-85128770051,10.3390/s22093273,thingsforsmartagricultureindevelopingcountries
...,...,...,...,...
8659,The influence of personal and organizational f...,2-s2.0-85071978981,10.3390/su11174804,databasemanagementsystemperformancecomparisons...
8660,Acceptability of quality reporting and pay for...,2-s2.0-84886688641,10.2190/HS.43.4.j,databasemanagementsystemperformancecomparisons...
8661,2013 2nd International Conference on Informati...,2-s2.0-84886442343,None,databasemanagementsystemperformancecomparisons...
8662,Indicators in primary care: Reality or desire....,2-s2.0-84857912481,10.1016/j.gaceta.2011.08.006,databasemanagementsystemperformancecomparisons...
8663,Potential Effectiveness of Comparative Casemis...,2-s2.0-0024546850,10.1177/0272989X8900900205,databasemanagementsystemperformancecomparisons...

In [13]:
def filter_col(df):
    df = df[[x for x in df.columns if x != "citingid" and x != "citeid" and "doi" not in x]]
    df = df.rename({"Paper title": "Cited paper title", "Paper eid": "Cited paper eid"}, axis=1)
    df["Cited paper link"] = df["Cited paper eid"].apply(lambda x: "https://www.scopus.com/record/display.uri?eid={}&origin=resultslist".format(x))
    df["Citing paper link"] = df["Citing paper eid"].apply(lambda x: "https://www.scopus.com/record/display.uri?eid={}&origin=resultslist".format(x))
    return df

In [14]:
filter_col(scopus_papers.merge(not_cited, on=["citeid"]).merge(missin_papers_scopus, on=["citingid"])).to_csv('data/missing-{}-all.csv'.format(time.time()), index=False)
filter_col(scopus_papers.merge(not_cited, on=["citeid"]).merge(missin_papers_scopus[missin_papers_scopus["citingid"] == missin_papers_scopus["Citing paper title"].apply(lambda x: map_id(x))], on=["citingid"])).to_csv('data/missing-{}-red.csv'.format(time.time()), index=False)