In [1]:
import pandas as pd
import pandas as pd
import glob
import os
import numpy as np

def map_id(x):
    if str(x).lower() == "nan":
        return np.nan
    return str(x).lower().replace('.', '').replace(' ', '').replace(':', '').replace('-', '').replace('\xa0', '').replace(',', '').replace('+', '').replace('<sup>', '').replace('</sup>', '')


def get_df(s, path = 'data/', onlylast=False):
    li = []
    files = glob.glob(os.path.join(path , s + "*.csv"))
    for filename in files if not onlylast else [files[-1]]:
        print(filename)
        df = pd.read_csv(filename, index_col=None, header=0, encoding='utf-8')
        li.append(df)
    all_df = pd.concat(li, axis=0, ignore_index=True)
    all_df = all_df.drop_duplicates().replace("", np.nan)
    all_df["citeid"] = all_df["Paper title"].apply(lambda x: map_id(x))
    all_df["citingid"] = all_df["Citing paper title"].apply(lambda x: map_id(x))
    return all_df

In [2]:
scholar = get_df('scholar-citations')  # get the scholar citations
scholar

data\scholar-citations-1676383226.4907641.csv
data\scholar-citations-1676390245.6953535.csv
data\scholar-citations-1676633623.8536773.csv
data\scholar-citations-1676902413.7930026.csv
data\scholar-citations-1677504445.7159173.csv
data\scholar-citations-1678117540.5000184.csv
data\scholar-citations-1678179464.9919195.csv
data\scholar-citations-1680517501.2175415.csv
data\scholar-citations-1681200623.1668324.csv
data\scholar-citations-1683799837.6045644.csv
data\scholar-citations-1684155368.4507754.csv
data\scholar-citations-1684156883.008631.csv
data\scholar-citations-1687853379.047738.csv
data\scholar-citations-1689857439.9302237.csv
data\scholar-citations-1690289205.1982708.csv
data\scholar-citations-1693231044.1924667.csv
data\scholar-citations-1695377342.630087.csv
data\scholar-citations-1696945101.1924646.csv
data\scholar-citations-1698932706.398716.csv
data\scholar-citations-1701939576.884364.csv
data\scholar-citations-1702892181.4055862.csv
data\scholar-citations.csv

,Paper title,Citing paper title,citeid,citingid
0,Crop management with the iot: An interdiscipli...,AgriFusion: An architecture for IoT and emergi...,cropmanagementwiththeiotaninterdisciplinarysurvey,agrifusionanarchitectureforiotandemergingtechn...
1,Crop management with the iot: An interdiscipli...,Everything you wanted to know about smart agri...,cropmanagementwiththeiotaninterdisciplinarysurvey,everythingyouwantedtoknowaboutsmartagriculture
2,Crop management with the iot: An interdiscipli...,Prediction of pest insect appearance using sen...,cropmanagementwiththeiotaninterdisciplinarysurvey,predictionofpestinsectappearanceusingsensorsan...
3,Crop management with the iot: An interdiscipli...,A smart and mechanized agricultural applicatio...,cropmanagementwiththeiotaninterdisciplinarysurvey,asmartandmechanizedagriculturalapplicationfrom...
4,Crop management with the iot: An interdiscipli...,Machine Learning in Precision Agriculture: A S...,cropmanagementwiththeiotaninterdisciplinarysurvey,machinelearninginprecisionagricultureasurveyon...
...,...,...,...,...
3454,A-BI+: a framework for Augmented Business Inte...,Soluci�n de inteligencia de negocios para el a...,abiaframeworkforaugmentedbusinessintelligence,soluci�ndeinteligenciadenegociosparaelaprovech...
3469,Social BI to understand the debate on vaccines...,Understanding public perceptions of COVID-19 c...,socialbitounderstandthedebateonvaccinesonthewe...,understandingpublicperceptionsofcovid19contact...
3489,Making data platforms smarter with MOSES,Ecossistemas de big data: uma revis�o sistem�tica,makingdataplatformssmarterwithmoses,ecossistemasdebigdataumarevis�osistem�tica
3515,Supporting the Generation of Data Narratives,Mod�liser la d�marche du data journaliste,supportingthegenerationofdatanarratives,mod�liserlad�marchedudatajournaliste
3516,Supporting the Generation of Data Narratives,Un mod�le conceptual de narration de donn�es,supportingthegenerationofdatanarratives,unmod�leconceptualdenarrationdedonn�es

In [3]:
scopus = get_df('scopus-citations', onlylast=True)  # get the scopus citations
scopus

data\scopus-citations-1703171554.6364958.csv

,Paper title,Paper eid,Paper doi,Citing paper title,Citing paper eid,Citing paper doi,citeid,citingid
0,HAMLET: A framework for Human-centered AutoML ...,2-s2.0-85145965157,10.1016/j.future.2022.12.035,NaN,NaN,NaN,hamletaframeworkforhumancenteredautomlviastruc...,NaN
1,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,Colossal Trajectory Mining: A unifying approac...,2-s2.0-85174707802,10.1016/j.eswa.2023.122055,trajectorybasedspatiotemporalentitylinking,colossaltrajectoryminingaunifyingapproachtomin...
2,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,Leveraging user itinerary to improve personali...,2-s2.0-85149039992,10.1007/s00778-023-00787-z,trajectorybasedspatiotemporalentitylinking,leveraginguseritinerarytoimprovepersonalizedde...
3,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,A Survey and Experimental Study on Privacy-Pre...,2-s2.0-85132525373,10.1109/TKDE.2022.3174204,trajectorybasedspatiotemporalentitylinking,asurveyandexperimentalstudyonprivacypreserving...
4,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,Information Resilience: the nexus of responsib...,2-s2.0-85123164859,10.1007/s00778-021-00720-2,trajectorybasedspatiotemporalentitylinking,informationresiliencethenexusofresponsibleanda...
...,...,...,...,...,...,...,...,...
184,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Modelling and simulation of Opportunistic IoT ...,2-s2.0-85053778744,10.1016/j.future.2018.09.005,towardsafoundationalapiforresilientdistributed...,modellingandsimulationofopportunisticiotservic...
185,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,The share operator for field-based coordination,2-s2.0-85067426015,10.1007/978-3-030-22397-7_4,towardsafoundationalapiforresilientdistributed...,theshareoperatorforfieldbasedcoordination
186,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,From field-based coordination to aggregate com...,2-s2.0-85048884985,10.1007/978-3-319-92408-3_12,towardsafoundationalapiforresilientdistributed...,fromfieldbasedcoordinationtoaggregatecomputing
187,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Practical Aggregate Programming with Protelis,2-s2.0-85035242264,10.1109/FAS-W.2017.186,towardsafoundationalapiforresilientdistributed...,practicalaggregateprogrammingwithprotelis
188,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Self-Stabilising Target Counting in Wireless S...,2-s2.0-85035210635,10.1109/SASO.2017.10,towardsafoundationalapiforresilientdistributed...,selfstabilisingtargetcountinginwirelesssensorn...

In [4]:
scopus.groupby(by=["citeid"])["citingid"].count().sort_values(ascending=False)

citeid
cropmanagementwiththeiotaninterdisciplinarysurvey                                                                26
towardsafoundationalapiforresilientdistributedsystemsdesign                                                      14
towardsconversationalolap                                                                                        12
towardsaconceptualmodelfordatanarratives                                                                         12
asurveyandexperimentalstudyonprivacypreservingtrajectorydatapublishing                                           11
trajectorybasedspatiotemporalentitylinking                                                                       10
makingdataplatformssmarterwithmoses                                                                              10
enhancingcubeswithmodelstodescribemultidimensionaldata                                                            9
abiaframeworkforaugmentedbusinessintelligence                                                                     9
coolaframeworkforconversationalolap                                                                               9
assessqueriesforinteractiveanalysisofdatacubes                                                                    8
augmentedbusinessintelligence                                                                                     7
socialbitounderstandthedebateonvaccinesonthewebandsocialmediaunravelingtheantifreeandprovaxcommunitiesinitaly     7
multisensorprofilingforprecisionsoilmoisturemonitoring                                                            6
summarizationandvisualizationofmultilevelandmultidimensionalitemsets                                              6
optimizingexecutionplansinamultistore                                                                             5
supportingthegenerationofdatanarratives                                                                           5
mapmatchingonbigdataadistributedandefficientalgorithmwithahiddenmarkovmodel                                       5
dartdeanonymizationofpersonalgazetteersthroughsocialtrajectories                                                  5
thetelltalecube                                                                                                   4
suggestingassessqueriesforinteractiveanalysisofmultidimensionaldata                                               1
insightbasedvocalizationofolapsessions                                                                            1
olapqueryingofdocumentstoresinthepresenceofschemavariety                                                          1
conversationalolapinaction                                                                                        1
asimilarityfunctionformultilevelandmultidimensionalitemsets                                                       1
conversationalolap                                                                                                0
hamletaframeworkforhumancenteredautomlviastructuredargumentation                                                  0
describingmultidimensionaldatathroughhighlights(discussionpaper)                                                  0
costbasedoptimizationofmultistorequeryplans                                                                       0
Name: citingid, dtype: int64

In [5]:
scopus_papers = scopus[["Paper title", "Paper eid", "Paper doi", "citeid"]].drop_duplicates().sort_values(by=["Paper title"]).reset_index(drop=True)
scopus_papers

,Paper title,Paper eid,Paper doi,citeid
0,A Similarity Function for Multi-Level and Mult...,2-s2.0-85051863772,NaN,asimilarityfunctionformultilevelandmultidimens...
1,A Survey and Experimental Study on Privacy-Pre...,2-s2.0-85132525373,10.1109/TKDE.2022.3174204,asurveyandexperimentalstudyonprivacypreserving...
2,A-BI<sup>+</sup>: A framework for Augmented Bu...,2-s2.0-85082441558,10.1016/j.is.2020.101520,abiaframeworkforaugmentedbusinessintelligence
3,Assess queries for interactive analysis of dat...,2-s2.0-85113712544,10.5441/002/edbt.2021.12,assessqueriesforinteractiveanalysisofdatacubes
4,Augmented business intelligence,2-s2.0-85062645475,NaN,augmentedbusinessintelligence
5,COOL: A framework for conversational OLAP,2-s2.0-85103428030,10.1016/j.is.2021.101752,coolaframeworkforconversationalolap
6,Conversational OLAP,2-s2.0-85118769792,NaN,conversationalolap
7,Conversational OLAP in action,2-s2.0-85113716450,10.5441/002/edbt.2021.74,conversationalolapinaction
8,Cost-based Optimization of Multistore Query Plans,2-s2.0-85139405955,10.1007/s10796-022-10320-2,costbasedoptimizationofmultistorequeryplans
9,Crop Management with the IoT: An Interdiscipli...,2-s2.0-85100942957,10.3390/agronomy11010181,cropmanagementwiththeiotaninterdisciplinarysurvey
10,DART: De-Anonymization of personal gazetteers ...,2-s2.0-85093926143,10.1016/j.jisa.2020.102634,dartdeanonymizationofpersonalgazetteersthrough...
11,Describing Multidimensional Data Through Highl...,2-s2.0-85137469232,NaN,describingmultidimensionaldatathroughhighlight...
12,Enhancing Cubes with Models to Describe Multid...,2-s2.0-85107683405,10.1007/s10796-021-10147-3,enhancingcubeswithmodelstodescribemultidimensi...
13,HAMLET: A framework for Human-centered AutoML ...,2-s2.0-85145965157,10.1016/j.future.2022.12.035,hamletaframeworkforhumancenteredautomlviastruc...
14,Insight-Based Vocalization of OLAP Sessions,2-s2.0-85137993971,10.1007/978-3-031-15740-0_15,insightbasedvocalizationofolapsessions
15,Making data platforms smarter with MOSES,2-s2.0-85109035166,10.1016/j.future.2021.06.031,makingdataplatformssmarterwithmoses
16,Map-matching on big data: A distributed and ef...,2-s2.0-85070329171,10.23919/MIPRO.2019.8757119,mapmatchingonbigdataadistributedandefficiental...
17,Multi-sensor profiling for precision soil-mois...,2-s2.0-85129541562,10.1016/j.compag.2022.106924,multisensorprofilingforprecisionsoilmoisturemo...
18,OLAP Querying of Document Stores in the Presen...,2-s2.0-85090883258,NaN,olapqueryingofdocumentstoresinthepresenceofsch...
19,Optimizing Execution Plans in a Multistore,2-s2.0-85115134032,10.1007/978-3-030-82472-3_11,optimizingexecutionplansinamultistore
20,Social BI to understand the debate on vaccines...,2-s2.0-85070525370,10.1007/s13278-019-0590-x,socialbitounderstandthedebateonvaccinesonthewe...
21,Suggesting assess queries for interactive anal...,2-s2.0-85129353199,10.1109/TKDE.2022.3171516,suggestingassessqueriesforinteractiveanalysiso...
22,Summarization and visualization of multi-level...,2-s2.0-85079239065,10.1016/j.ins.2020.02.006,summarizationandvisualizationofmultilevelandmu...
23,Supporting the generation of data narratives,2-s2.0-85095734112,NaN,supportingthegenerationofdatanarratives
24,The Tell-Tale Cube,2-s2.0-85090100247,10.1007/978-3-030-54832-2_16,thetelltalecube
25,Towards a Conceptual Model for Data Narratives,2-s2.0-85097380415,10.1007/978-3-030-62522-1_19,towardsaconceptualmodelfordatanarratives
26,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,towardsafoundationalapiforresilientdistributed...
27,Towards conversational OLAP,2-s2.0-85082444588,NaN,towardsconversationalolap
28,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,trajectorybasedspatiotemporalentitylinking

In [6]:
scopus_papers.groupby(by=["citeid"]).count().reset_index()

,citeid,Paper title,Paper eid,Paper doi
0,abiaframeworkforaugmentedbusinessintelligence,1,1,1
1,asimilarityfunctionformultilevelandmultidimens...,1,1,0
2,assessqueriesforinteractiveanalysisofdatacubes,1,1,1
3,asurveyandexperimentalstudyonprivacypreserving...,1,1,1
4,augmentedbusinessintelligence,1,1,0
5,conversationalolap,1,1,0
6,conversationalolapinaction,1,1,1
7,coolaframeworkforconversationalolap,1,1,1
8,costbasedoptimizationofmultistorequeryplans,1,1,1
9,cropmanagementwiththeiotaninterdisciplinarysurvey,1,1,1
10,dartdeanonymizationofpersonalgazetteersthrough...,1,1,1
11,describingmultidimensionaldatathroughhighlight...,1,1,0
12,enhancingcubeswithmodelstodescribemultidimensi...,1,1,1
13,hamletaframeworkforhumancenteredautomlviastruc...,1,1,1
14,insightbasedvocalizationofolapsessions,1,1,1
15,makingdataplatformssmarterwithmoses,1,1,1
16,mapmatchingonbigdataadistributedandefficiental...,1,1,1
17,multisensorprofilingforprecisionsoilmoisturemo...,1,1,1
18,olapqueryingofdocumentstoresinthepresenceofsch...,1,1,0
19,optimizingexecutionplansinamultistore,1,1,1
20,socialbitounderstandthedebateonvaccinesonthewe...,1,1,1
21,suggestingassessqueriesforinteractiveanalysiso...,1,1,1
22,summarizationandvisualizationofmultilevelandmu...,1,1,1
23,supportingthegenerationofdatanarratives,1,1,0
24,thetelltalecube,1,1,1
25,towardsaconceptualmodelfordatanarratives,1,1,1
26,towardsafoundationalapiforresilientdistributed...,1,1,1
27,towardsconversationalolap,1,1,0
28,trajectorybasedspatiotemporalentitylinking,1,1,1

In [7]:
scopus_lookup = {}
for x in scopus_papers.to_numpy():
    scopus_lookup[x[3]] = x[:3]
scopus_lookup

{'asimilarityfunctionformultilevelandmultidimensionalitemsets': array(['A Similarity Function for Multi-Level and Multi-Dimensional Itemsets',
        '2-s2.0-85051863772', nan], dtype=object),
 'asurveyandexperimentalstudyonprivacypreservingtrajectorydatapublishing': array(['A Survey and Experimental Study on Privacy-Preserving Trajectory Data Publishing',
        '2-s2.0-85132525373', '10.1109/TKDE.2022.3174204'], dtype=object),
 'abiaframeworkforaugmentedbusinessintelligence': array(['A-BI<sup>+</sup>: A framework for Augmented Business Intelligence',
        '2-s2.0-85082441558', '10.1016/j.is.2020.101520'], dtype=object),
 'assessqueriesforinteractiveanalysisofdatacubes': array(['Assess queries for interactive analysis of data cubes',
        '2-s2.0-85113712544', '10.5441/002/edbt.2021.12'], dtype=object),
 'augmentedbusinessintelligence': array(['Augmented business intelligence', '2-s2.0-85062645475', nan],
       dtype=object),
 'coolaframeworkforconversationalolap': array(['COOL: A framework for conversational OLAP', '2-s2.0-85103428030',
        '10.1016/j.is.2021.101752'], dtype=object),
 'conversationalolap': array(['Conversational OLAP', '2-s2.0-85118769792', nan], dtype=object),
 'conversationalolapinaction': array(['Conversational OLAP in action', '2-s2.0-85113716450',
        '10.5441/002/edbt.2021.74'], dtype=object),
 'costbasedoptimizationofmultistorequeryplans': array(['Cost-based Optimization of Multistore Query Plans',
        '2-s2.0-85139405955', '10.1007/s10796-022-10320-2'], dtype=object),
 'cropmanagementwiththeiotaninterdisciplinarysurvey': array(['Crop Management with the IoT: An Interdisciplinary Survey',
        '2-s2.0-85100942957', '10.3390/agronomy11010181'], dtype=object),
 'dartdeanonymizationofpersonalgazetteersthroughsocialtrajectories': array(['DART: De-Anonymization of personal gazetteers through social trajectories',
        '2-s2.0-85093926143', '10.1016/j.jisa.2020.102634'], dtype=object),
 'describingmultidimensionaldatathroughhighlights(discussionpaper)': array(['Describing Multidimensional Data Through Highlights (Discussion Paper)',
        '2-s2.0-85137469232', nan], dtype=object),
 'enhancingcubeswithmodelstodescribemultidimensionaldata': array(['Enhancing Cubes with Models to Describe Multidimensional Data',
        '2-s2.0-85107683405', '10.1007/s10796-021-10147-3'], dtype=object),
 'hamletaframeworkforhumancenteredautomlviastructuredargumentation': array(['HAMLET: A framework for Human-centered AutoML via Structured Argumentation',
        '2-s2.0-85145965157', '10.1016/j.future.2022.12.035'], dtype=object),
 'insightbasedvocalizationofolapsessions': array(['Insight-Based Vocalization of\xa0OLAP Sessions',
        '2-s2.0-85137993971', '10.1007/978-3-031-15740-0_15'], dtype=object),
 'makingdataplatformssmarterwithmoses': array(['Making data platforms smarter with MOSES', '2-s2.0-85109035166',
        '10.1016/j.future.2021.06.031'], dtype=object),
 'mapmatchingonbigdataadistributedandefficientalgorithmwithahiddenmarkovmodel': array(['Map-matching on big data: A distributed and efficient algorithm with a hidden Markov model',
        '2-s2.0-85070329171', '10.23919/MIPRO.2019.8757119'], dtype=object),
 'multisensorprofilingforprecisionsoilmoisturemonitoring': array(['Multi-sensor profiling for precision soil-moisture monitoring',
        '2-s2.0-85129541562', '10.1016/j.compag.2022.106924'], dtype=object),
 'olapqueryingofdocumentstoresinthepresenceofschemavariety': array(['OLAP Querying of Document Stores in the Presence of Schema Variety',
        '2-s2.0-85090883258', nan], dtype=object),
 'optimizingexecutionplansinamultistore': array(['Optimizing Execution Plans in a Multistore', '2-s2.0-85115134032',
        '10.1007/978-3-030-82472-3_11'], dtype=object),
 'socialbitounderstandthedebateonvaccinesonthewebandsocialmediaunravelingtheantifreeandprovaxcommunitiesinitaly': array(['Social BI to understand the debate on vaccines on the Web and social media: unraveling the anti-, free, and pro-vax communities in Italy',
        '2-s2.0-85070525370', '10.1007/s13278-019-0590-x'], dtype=object),
 'suggestingassessqueriesforinteractiveanalysisofmultidimensionaldata': array(['Suggesting assess queries for interactive analysis of multidimensional data',
        '2-s2.0-85129353199', '10.1109/TKDE.2022.3171516'], dtype=object),
 'summarizationandvisualizationofmultilevelandmultidimensionalitemsets': array(['Summarization and visualization of multi-level and multi-dimensional itemsets',
        '2-s2.0-85079239065', '10.1016/j.ins.2020.02.006'], dtype=object),
 'supportingthegenerationofdatanarratives': array(['Supporting the generation of data narratives',
        '2-s2.0-85095734112', nan], dtype=object),
 'thetelltalecube': array(['The Tell-Tale Cube', '2-s2.0-85090100247',
        '10.1007/978-3-030-54832-2_16'], dtype=object),
 'towardsaconceptualmodelfordatanarratives': array(['Towards a Conceptual Model for Data Narratives',
        '2-s2.0-85097380415', '10.1007/978-3-030-62522-1_19'], dtype=object),
 'towardsafoundationalapiforresilientdistributedsystemsdesign': array(['Towards a foundational API for resilient distributed systems design',
        '2-s2.0-85035209468', '10.1109/FAS-W.2017.116'], dtype=object),
 'towardsconversationalolap': array(['Towards conversational OLAP', '2-s2.0-85082444588', nan],
       dtype=object),
 'trajectorybasedspatiotemporalentitylinking': array(['Trajectory-Based Spatiotemporal Entity Linking',
        '2-s2.0-85096846619', '10.1109/TKDE.2020.3036633'], dtype=object)}

In [8]:
scopus_unique = scopus["citeid"].sort_values().unique()
scopus_unique

array(['abiaframeworkforaugmentedbusinessintelligence',
       'asimilarityfunctionformultilevelandmultidimensionalitemsets',
       'assessqueriesforinteractiveanalysisofdatacubes',
       'asurveyandexperimentalstudyonprivacypreservingtrajectorydatapublishing',
       'augmentedbusinessintelligence', 'conversationalolap',
       'conversationalolapinaction',
       'coolaframeworkforconversationalolap',
       'costbasedoptimizationofmultistorequeryplans',
       'cropmanagementwiththeiotaninterdisciplinarysurvey',
       'dartdeanonymizationofpersonalgazetteersthroughsocialtrajectories',
       'describingmultidimensionaldatathroughhighlights(discussionpaper)',
       'enhancingcubeswithmodelstodescribemultidimensionaldata',
       'hamletaframeworkforhumancenteredautomlviastructuredargumentation',
       'insightbasedvocalizationofolapsessions',
       'makingdataplatformssmarterwithmoses',
       'mapmatchingonbigdataadistributedandefficientalgorithmwithahiddenmarkovmodel',
       'multisensorprofilingforprecisionsoilmoisturemonitoring',
       'olapqueryingofdocumentstoresinthepresenceofschemavariety',
       'optimizingexecutionplansinamultistore',
       'socialbitounderstandthedebateonvaccinesonthewebandsocialmediaunravelingtheantifreeandprovaxcommunitiesinitaly',
       'suggestingassessqueriesforinteractiveanalysisofmultidimensionaldata',
       'summarizationandvisualizationofmultilevelandmultidimensionalitemsets',
       'supportingthegenerationofdatanarratives', 'thetelltalecube',
       'towardsaconceptualmodelfordatanarratives',
       'towardsafoundationalapiforresilientdistributedsystemsdesign',
       'towardsconversationalolap',
       'trajectorybasedspatiotemporalentitylinking'], dtype=object)

In [9]:
scholar_unique = scholar["citeid"].sort_values().unique()
scholar_unique

array(['abiaframeworkforaugmentedbusinessintelligence',
       'asimilarityfunctionformultilevelandmultidimensionalitemsets',
       'assessqueriesforinteractiveanalysisofdatacubes',
       'asurveyandexperimentalstudyonprivacypreservingtrajectorydatapublishing',
       'augmentedbusinessintelligence', 'conversationalolapinaction',
       'coolaframeworkforconversationalolap',
       'costbasedoptimizationofmultistorequeryplans',
       'cropmanagementwiththeiotaninterdisciplinarysurvey',
       'dartdeanonymizationofpersonalgazetteersthroughsocialtrajectories',
       'enhancingcubeswithmodelstodescribemultidimensionaldata',
       'exploitingtheinternetresourcesforautonomousrobotsinagriculture',
       'hamletaframeworkforhumancenteredautomlviastructuredargumentation',
       'makingdataplatformssmarterwithmoses',
       'mapmatchingonbigdataadistributedandefficientalgorithmwithahiddenmarkovmodel',
       'multisensorprofilingforprecisionsoilmoisturemonitoring',
       'olapqueryingofdocumentstoresinthepresenceofschemavariety',
       'optimizingexecutionplansinamultistore',
       'socialbitounderstandthedebateonvaccinesonthewebandsocialmediaunravelingtheantifreeandprovaxcommunitiesinitaly',
       'suggestingassessqueriesforinteractiveanalysisofmultidimensionaldata',
       'summarizationandvisualizationofmultilevelandmultidimensionalitemsets',
       'supportingthegenerationofdatanarratives', 'thetelltalecube',
       'thewhysandwhereforesofcubes',
       'towardsaconceptualmodelfordatanarratives',
       'towardsafoundationalapiforresilientdistributedsystemsdesign',
       'towardsconversationalolap',
       'trajectorybasedspatiotemporalentitylinking'], dtype=object)

In [10]:
not_cited_ids = []
for x in scholar_unique:  # for each paper in scholar
    citations_scholar = scholar[scholar["citeid"] == x]  # get its citing papers from scholar
    paper_scopus = scopus[(scopus["citeid"] == x)]  # get the paper from scopus...
    if len(paper_scopus) == 0:  # if the paper is not on scopus...
        print(x + " is not in scopus")
    else:
        for y in citations_scholar["citingid"].unique():  # for each of the citing papers from scholar
            if len(paper_scopus[(scopus["citingid"] == y)]) == 0:  # if this citation is not in scopus...
                not_cited_ids.append([x, y])  # add it
not_cited = pd.DataFrame(not_cited_ids, columns=["citeid", "citingid"])
not_cited

exploitingtheinternetresourcesforautonomousrobotsinagriculture is not in scopus
thewhysandwhereforesofcubes is not in scopus

C:\Users\matteo.francia5\AppData\Local\Temp\ipykernel_24936\698780769.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if len(paper_scopus[(scopus["citingid"] == y)]) == 0:  # if this citation is not in scopus...

,citeid,citingid
0,abiaframeworkforaugmentedbusinessintelligence,lainteligenciadenegociosylaanalíticadedatosenl...
1,abiaframeworkforaugmentedbusinessintelligence,theimpactofbusinessintelligencecharacteristics...
2,abiaframeworkforaugmentedbusinessintelligence,augmentingtheknowledgepyramidwithunconventiona...
3,abiaframeworkforaugmentedbusinessintelligence,lainteligenciadenegociosylaanalíticadedatosenl...
4,abiaframeworkforaugmentedbusinessintelligence,solucióndeinteligenciadenegociosparaelaprovech...
...,...,...
124,towardsconversationalolap,describingmultidimensionaldatathroughhighlights
125,trajectorybasedspatiotemporalentitylinking,augmentingtheknowledgepyramidwithunconventiona...
126,trajectorybasedspatiotemporalentitylinking,trajectoryuserlinkingviahierarchicalspatiotemp...
127,trajectorybasedspatiotemporalentitylinking,astudyonprivacyprotectiontechniquesforspatiote...
128,trajectorybasedspatiotemporalentitylinking,efficientfrequencybasedrandomizationforspatial...

In [11]:
missing_papers = scholar[["Citing paper title", "citingid"]].drop_duplicates().merge(not_cited, on=["citingid"])
missing_papers

,Citing paper title,citingid,citeid
0,Everything you wanted to know about smart agri...,everythingyouwantedtoknowaboutsmartagriculture,cropmanagementwiththeiotaninterdisciplinarysurvey
1,Analysis of chlorophyll and carotenoids conten...,analysisofchlorophyllandcarotenoidscontentinbr...,cropmanagementwiththeiotaninterdisciplinarysurvey
2,LambdAgrIoT: a new architecture for agricultur...,lambdagriotanewarchitectureforagriculturalauto...,cropmanagementwiththeiotaninterdisciplinarysurvey
3,An Intelligent Agro-Cloud Framework For Effici...,anintelligentagrocloudframeworkforefficientcro...,cropmanagementwiththeiotaninterdisciplinarysurvey
4,A model for automatized data integration in ha...,amodelforautomatizeddataintegrationinhadoopbas...,cropmanagementwiththeiotaninterdisciplinarysurvey
...,...,...,...
127,The Impact of Business Intelligence Characteri...,theimpactofbusinessintelligencecharacteristics...,abiaframeworkforaugmentedbusinessintelligence
128,La inteligencia de negocios y la anal�tica de ...,lainteligenciadenegociosylaanal�ticadedatosenl...,abiaframeworkforaugmentedbusinessintelligence
129,Soluci�n de inteligencia de negocios para el a...,soluci�ndeinteligenciadenegociosparaelaprovech...,abiaframeworkforaugmentedbusinessintelligence
130,Understanding public perceptions of COVID-19 c...,understandingpublicperceptionsofcovid19contact...,socialbitounderstandthedebateonvaccinesonthewe...
131,Ecossistemas de big data: uma revis�o sistem�tica,ecossistemasdebigdataumarevis�osistem�tica,makingdataplatformssmarterwithmoses

In [12]:
scopus_acc = []
not_in_scopus = []
missin_papers_scopus = pd.DataFrame(scopus_acc, columns=["Citing paper title", "Citing paper eid", "Citing paper doi", "citingid"])
missin_papers_scopus

Empty DataFrame
Columns: [Citing paper title, Citing paper eid, Citing paper doi, citingid]
Index: []

In [13]:
import pybliometrics
from pybliometrics.scopus import ScopusSearch
from pybliometrics.scopus.utils import config
from pybliometrics.scopus import AuthorRetrieval
import sys
import pandas as pd
import time
from random import shuffle
import re

def map_string(x):
    skip_words = [":", "'", " and ", " or ", " of ", " the ", "-"]
    x = x.lower()
    for s in skip_words:
        x = x.replace(s, " ")
    _RE_COMBINE_WHITESPACE = re.compile(r"\s+")
    x = _RE_COMBINE_WHITESPACE.sub(" ", x).strip()
    return x

xx = list(missing_papers[["Citing paper title", "citingid"]].drop_duplicates().to_numpy())
shuffle(xx)
for x in xx: #[["PUTS: Privacy-Preserving and Utility-Enhancing Framework for Trajectory Synthesization", "foo"]]:
    string = "TITLE-ABS-KEY({})".format(' AND '.join(map_string(x[0]).split(' ')))
    try:
        s = ScopusSearch(string)
        # print(string)
        # print(s.results)
        if s.results is not None and len(s.results) > 0:
            papers = [[y.title, y.eid, y.doi, x[1]] for y in s.results]
            for paper in papers:
                scopus_acc = scopus_acc + [paper]
                missin_papers_scopus = pd.DataFrame(scopus_acc, columns=["Citing paper title", "Citing paper eid", "Citing paper doi", "citingid"]).drop_duplicates()
        else:
            not_in_scopus = not_in_scopus + [x[0]]
        time.sleep(1)
    except Exception as e:
        print(x[0] + " " + string + ": " + str(e) + "\n")

La inteligencia de negocios y la anal�tica de datos en los procesos empresariales TITLE-ABS-KEY(la AND inteligencia AND de AND negocios AND y AND la AND anal�tica AND de AND datos AND en AND los AND procesos AND empresariales): Error translating query

La inteligencia de negocios y la anal�tica de datos en los procesos empresariales Business intelligence and data analytics in business processes TITLE-ABS-KEY(la AND inteligencia AND de AND negocios AND y AND la AND anal�tica AND de AND datos AND en AND los AND procesos AND empresariales AND business AND intelligence AND data AND analytics AND in AND business AND processes): Error translating query

Understanding public perceptions of COVID-19 contact tracing apps: Artificial intelligence�enabled social media analysis TITLE-ABS-KEY(understanding AND public AND perceptions AND covid AND 19 AND contact AND tracing AND apps AND artificial AND intelligence�enabled AND social AND media AND analysis): Error translating query

Un mod�le conceptual de narration de donn�es TITLE-ABS-KEY(un AND mod�le AND conceptual AND de AND narration AND de AND donn�es): Error translating query

Ecossistemas de big data: uma revis�o sistem�tica TITLE-ABS-KEY(ecossistemas AND de AND big AND data AND uma AND revis�o AND sistem�tica): Error translating query

The Impact of Business Intelligence Characteristics on Competitiveness of Companies with the Mediating Role of Entrepreneurship, Market Orientation and Business � TITLE-ABS-KEY(the AND impact AND business AND intelligence AND characteristics AND on AND competitiveness AND companies AND with AND mediating AND role AND entrepreneurship, AND market AND orientation AND business AND �): Error translating query

Mod�liser la d�marche du data journaliste TITLE-ABS-KEY(mod�liser AND la AND d�marche AND du AND data AND journaliste): Error translating query

Soluci�n de inteligencia de negocios para el aprovechamiento de los datos del servicio m�dico en una entidad bancaria TITLE-ABS-KEY(soluci�n AND de AND inteligencia AND de AND negocios AND para AND el AND aprovechamiento AND de AND los AND datos AND del AND servicio AND m�dico AND en AND una AND entidad AND bancaria): Error translating query

Fouille de s�quences de mobilit� s�mantique: sur l'�laboration de mesures pour la comparaison, l'analyse et la d�couverte de comportements TITLE-ABS-KEY(fouille AND de AND s�quences AND de AND mobilit� AND s�mantique AND sur AND l AND �laboration AND de AND mesures AND pour AND la AND comparaison, AND l AND analyse AND et AND la AND d�couverte AND de AND comportements): Error translating query

In [14]:
not_in_scopus

['Ecossistemas de big data: uma revisão sistemática',
 'Everything you wanted to know about smart agriculture',
 'A model for automatized data integration in hadoop-based data lakes',
 'Distributed and Decentralized Algorithms for Functional Programmable Matter',
 'Un modèle conceptual de narration de données',
 'Towards Privacy Preservation using Clustering based Anonymization: Recent Advances and Future Research Outlook',
 'Understanding Privacy Risks of High-accuracy Radio Positioning and Sensing in Wireless Networks',
 'Potential and Trends of IoT Application in Agriculture in Vietnam',
 'تاثیر ویژگیهای هوشتجاری بر رقابتپذیری شرکتها با نقش میانجی کارآفرینی محوری، بازارمحوری و نوآوری در کسبوکار',
 'İŞLETMECİLİK, PAZARLAMA VE KÜLTÜR PERSPEKTİFİNDEN TURİZM',
 'PROGETTAZIONE E PROTOTIPAZIONE DI UN FRAMEWORK PER CONVERSATIONAL OLAP',
 'Towards Anonymizing Intermodal Mobility Data for Smart Cities',
 "Parents' Decisions to Vaccinate Children against COVID-19: A Scoping Review. Vaccines 2021, 9, 1476",
 'A Privacy-Preserving Trajectory Synthesis Method Based on Vector Translation Invariance Supporting Traffic Constraints',
 'Beyond Dashboards? Designing Data Stories for Effective Use in Business Intelligence and Analytics',
 'La inteligencia de negocios y la analítica de datos en los procesos empresariales Business intelligence and data analytics in business processes',
 'Interactive Hyperparameter Optimization in Multi-Objective Problems via Preference Learning',
 'تاثیر ویژگی\u200cهای هوش\u200cتجاری بر رقابت\u200cپذیری شرکت\u200cها با نقش میانجی کارآفرینی محوری، بازارمحوری و نوآوری در کسب\u200cوکار\u200e',
 'Faster Access Of Credit Cards Through Data Cube Technology',
 'Business Intelligence: vers un ETL à la demande sur des bases de données orientées documents',
 'Modéliser la démarche du data journaliste',
 'Connecting the Dots: Refugee Data Narratives',
 'Concepts towards an automated data pre-processing and preparation within data lakes',
 'BEYOND DASHBOARDS? DESIGNING DATA STORIES FOR EFFECTIVE USE IN BUSINESS INTELLIGENCE AND ANALYTICS',
 'The Adoption of the Internet of Things for SMART Agriculture in Zimbabwe',
 'Enhancing Efficiency and Data Utility in Longitudinal Data Anonymization',
 'Augmenting the Knowledge Pyramid with Unconventional Data and Advanced Analytics',
 'Progettazione di una piattaforma web per la simulazione di programmi aggregati',
 'La inteligencia de negocios y la analítica de datos en los procesos empresariales',
 'P18-An IoT electronic fence for agri-robots',
 'FABULA: Intelligence Report Generation Using Retrieval-Augmented Narrative Construction',
 'Evolving map matching with markov decision processes',
 'An Intelligent Agro-Cloud Framework For Efficient Crop Cultivation',
 'Serviz: A Visual Analytics System for the Analysis of Sequential Rules and its Application to Airport Ground Handling Operations',
 'Business Intelligence: towards on-demand ETL over document stores',
 'THE ADOPTION OF THE INTERNET OF THINGS FOR SMART AGRICULTURE IN ZIMBABWE',
 'Designing a Star Schema for Optimizing the Total Sales of Motorcycles',
 "Fouille de séquences de mobilité sémantique: sur l'élaboration de mesures pour la comparaison, l'analyse et la découverte de comportements",
 'Trajectory-User Linking via Hierarchical Spatio-Temporal Attention Networks',
 'A Python Package to Detect Anti-Vaccine Users on Twitter',
 'Solución de inteligencia de negocios para el aprovechamiento de los datos del servicio médico en una entidad bancaria',
 '都市農業地域のスマート農業技術ニーズの評価 東京都内における比較分析',
 'SeRViz: an interactive visualization framework for the analysis of sequential rules and frequent itemsets',
 'Evaluation of the Accuracy of the Remote Determination of the Brewster Angle When Measuring Physicochemical Parameters of Soil',
 'A Multi-Start Simulated Annealing Strategy for Data Lake Organization Problem',
 'The Impact of Business Intelligence Characteristics on Competitiveness of Companies with the Mediating Role of Entrepreneurship, Market Orientation and Business …',
 'Generalization of deep learning models applied to semantic segmentation of in-field natural images in vineyards',
 'A Path Model of the Intention to Adopt Variable Rate Irrigation in Northeast Italy. Sustainability 2021, 13, 1879']

In [15]:
missin_papers_scopus

,Citing paper title,Citing paper eid,Citing paper doi,citingid
0,LambdAgrIoT: a new architecture for agricultur...,2-s2.0-85140242438,10.1007/s10586-022-03592-5,lambdagriotanewarchitectureforagriculturalauto...
1,A collaborative perception method of human-urb...,2-s2.0-85144818337,10.1016/j.engappai.2022.105746,visualinformatics
2,Computer-Assisted analysis of routine electroe...,2-s2.0-85147047950,10.1136/bmjopen-2022-066932,visualinformatics
3,Mapping the knowledge of traffic collision Rec...,2-s2.0-85141787637,10.1016/j.scijus.2022.10.005,visualinformatics
4,"Evaluation, Comparison and Monitoring of Multi...",2-s2.0-85144591826,10.3390/a15120468,visualinformatics
...,...,...,...,...
14234,Re-Imagining the Future: Experiencing Sustaine...,2-s2.0-84979895709,10.1016/B978-0-12-804132-1.00011-1,thingsforsmartagricultureindevelopingcountries
14235,LDPTrace: Locally Differentially Private Traje...,2-s2.0-85153584578,10.14778/3594512.3594520,ldptracelocallydifferentiallyprivatetrajectory...
14236,Parents’ decisions to vaccinate children again...,2-s2.0-85121534481,10.3390/vaccines9121476,parents'decisionstovaccinatechildrenagainstcov...
14237,Holomorphic differentials of Klein four covers,2-s2.0-85151817306,10.1016/j.jpaa.2023.107384,holomorphicdifferentialsofkleinfourcovers
14238,Fabrication and investigation of agricultural ...,2-s2.0-85176146606,10.1007/s42452-023-05526-1,fabricationandinvestigationofagriculturalmonit...

In [16]:
def filter_col(df):
    df = df[[x for x in df.columns if x != "citingid" and x != "citeid" and "doi" not in x]]
    df = df.rename({"Paper title": "Cited paper title", "Paper eid": "Cited paper eid"}, axis=1)
    df["Cited paper link"] = df["Cited paper eid"].apply(lambda x: "https://www.scopus.com/record/display.uri?eid={}&origin=resultslist".format(x))
    df["Citing paper link"] = df["Citing paper eid"].apply(lambda x: "https://www.scopus.com/record/display.uri?eid={}&origin=resultslist".format(x))
    return df

In [17]:
filter_col(scopus_papers.merge(not_cited, on=["citeid"]).merge(missin_papers_scopus, on=["citingid"])).sort_values(by=['Cited paper title', 'Citing paper title']).to_csv('data/missing-{}-all.csv'.format(time.time()), index=False)
filter_col(scopus_papers.merge(not_cited, on=["citeid"]).merge(missin_papers_scopus[missin_papers_scopus["citingid"] == missin_papers_scopus["Citing paper title"].apply(lambda x: map_id(x))], on=["citingid"])).sort_values(by=['Cited paper title', 'Citing paper title']).to_csv('data/missing-{}-red.csv'.format(time.time()), index=False)