In [164]:
import pandas as pd
import glob
import os
import numpy as np

def map_id(x):
    if str(x).lower() == "nan":
        return np.nan
    return str(x).lower().replace('.', '').replace(' ', '').replace(':', '').replace('\'', '').replace('-', '').replace('?', '').replace('\xa0', '').replace(',', '').replace('+', '').replace('<sup>', '').replace('</sup>', '').replace('(discussionpaper)', '')


def get_df(s, path = '/home/data/', onlylast=False):
    i = 0
    li = []
    files = glob.glob(os.path.join(path , s + "*.csv"))
    for filename in files if not onlylast else [files[-1]]:
        # print(f"{i} {filename}")
        # i += 1
        df = pd.read_csv(filename, index_col=None, header=0, encoding='utf-8')
        li.append(df)
    all_df = pd.concat(li, axis=0, ignore_index=True)
    all_df = all_df.drop_duplicates().replace("", np.nan)
    all_df["citeid"] = all_df["Paper title"].apply(lambda x: map_id(x))
    all_df["citingid"] = all_df["Citing paper title"].apply(lambda x: map_id(x))
    return all_df

In [165]:
scholar = get_df('scholar-citations')  # get the scholar citations
scholar["Paper title"].nunique()
list(scholar["Paper title"].unique())

['Crop management with the iot: An interdisciplinary survey',
 'Towards a foundational API for resilient distributed systems design',
 'Towards a conceptual model for data narratives',
 'A-BI+: a framework for Augmented Business Intelligence',
 'Towards Conversational OLAP',
 'Social BI to understand the debate on vaccines on the Web and social media: Unraveling the anti-, free, and pro-vax communities in Italy',
 'COOL: A framework for conversational OLAP',
 'Making data platforms smarter with MOSES',
 'Trajectory-based spatiotemporal entity linking',
 'Summarization and visualization of multi-level and multi-dimensional itemsets',
 'Supporting the Generation of Data Narratives',
 'Augmented Business Intelligence.',
 'Assess queries for interactive analysis of data cubes',
 'A survey and experimental study on privacy-preserving trajectory data publishing',
 'Enhancing cubes with models to describe multidimensional data',
 'DART: De-Anonymization of personal gazetteers through social trajectories',
 'The tell-tale cube',
 'Map-matching on big data: A distributed and efficient algorithm with a hidden Markov model',
 'Conversational OLAP in action',
 'Optimizing execution plans in a multistore',
 'OLAP Querying of Document Stores in the Presence of Schema Variety',
 'A Similarity Function for Multi-Level and Multi-Dimensional Itemsets',
 'Cost-based Optimization of Multistore Query Plans',
 'Suggesting assess queries for interactive analysis of multidimensional data',
 'Multi-sensor profiling for precision soil-moisture monitoring',
 'Social BI to understand the debate on vaccines on the Web and social media: unraveling the anti-, free, and pro-vax communities in Italy',
 'Exploiting the Internet Resources for Autonomous Robots in Agriculture',
 'HAMLET: A framework for Human-centered AutoML via Structured Argumentation',
 'The Whys and Wherefores of Cubes',
 'Cost-based optimization of multistore query plans',
 'The Whys and Wherefores of Cubes.',
 'Streaming Approach to Schema Profiling',
 'Insight-based vocalization of OLAP sessions',
 'Colossal Trajectory Mining: A unifying approach to mine behavioral mobility patterns',
 'Describing Multidimensional Data Through Highlights',
 'Colossal trajectory mining: a unifying approach to mine behavioral mobility patterns',
 'Smart irrigation system for precision water management: effect on yield and fruit quality of yellow fleshed kiwifruit in northern Italy',
 'Dynamic Stream Clustering for Real-Time Schema Profiling with Dsc+',
 'The whys and wherefores of cubes',
 'Exploiting the internet resources for autonomous robots in agriculture',
 'An auto-tuning process-based 3D model to forecast irrigation demand in kiwifruit',
 'Towards a Process-Driven Design of Data Platforms']

In [166]:
scopus = get_df('scopus-citations', onlylast=True)  # get the scopus citations
scopus

,Paper title,Paper eid,Paper doi,Citing paper title,Citing paper eid,Citing paper doi,citeid,citingid
0,Process-driven design of cloud data platforms,2-s2.0-85216873928,10.1016/j.is.2025.102527,NaN,NaN,NaN,processdrivendesignofclouddataplatforms,NaN
1,Automating materiality assessment with a data-...,2-s2.0-85213286497,10.1016/j.jjimei.2024.100310,NaN,NaN,NaN,automatingmaterialityassessmentwithadatadriven...,NaN
2,An auto-tuning process-based 3D model to forec...,2-s2.0-85212101165,10.1016/j.ecoinf.2024.102947,NaN,NaN,NaN,anautotuningprocessbased3dmodeltoforecastirrig...,NaN
3,VOOL: A modular insight-based framework for vo...,2-s2.0-85211035819,10.1016/j.is.2024.102496,NaN,NaN,NaN,voolamodularinsightbasedframeworkforvocalizing...,NaN
4,Colossal Trajectory Mining: A unifying approac...,2-s2.0-85174707802,10.1016/j.eswa.2023.122055,Particle filtering supported probability densi...,2-s2.0-85190319631,10.1016/j.heliyon.2024.e29437,colossaltrajectoryminingaunifyingapproachtomin...,particlefilteringsupportedprobabilitydensityes...
...,...,...,...,...,...,...,...,...
1146,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Modelling and simulation of Opportunistic IoT ...,2-s2.0-85053778744,10.1016/j.future.2018.09.005,towardsafoundationalapiforresilientdistributed...,modellingandsimulationofopportunisticiotservic...
1147,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,The share operator for field-based coordination,2-s2.0-85067426015,10.1007/978-3-030-22397-7_4,towardsafoundationalapiforresilientdistributed...,theshareoperatorforfieldbasedcoordination
1148,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,From field-based coordination to aggregate com...,2-s2.0-85048884985,10.1007/978-3-319-92408-3_12,towardsafoundationalapiforresilientdistributed...,fromfieldbasedcoordinationtoaggregatecomputing
1149,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Practical Aggregate Programming with Protelis,2-s2.0-85035242264,10.1109/FAS-W.2017.186,towardsafoundationalapiforresilientdistributed...,practicalaggregateprogrammingwithprotelis
1150,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Self-Stabilising Target Counting in Wireless S...,2-s2.0-85035210635,10.1109/SASO.2017.10,towardsafoundationalapiforresilientdistributed...,selfstabilisingtargetcountinginwirelesssensorn...

In [167]:
scopus.groupby(by=["citeid"])["citingid"].count().sort_values(ascending=False)

citeid
makingdataplatformssmarterwithmoses                                                                              837
cropmanagementwiththeiotaninterdisciplinarysurvey                                                                 42
asurveyandexperimentalstudyonprivacypreservingtrajectorydatapublishing                                            40
towardsaconceptualmodelfordatanarratives                                                                          17
enhancingcubeswithmodelstodescribemultidimensionaldata                                                            15
abiaframeworkforaugmentedbusinessintelligence                                                                     15
trajectorybasedspatiotemporalentitylinking                                                                        15
towardsafoundationalapiforresilientdistributedsystemsdesign                                                       15
exploitingtheinternetresourcesforautonomousrobotsinagriculture                                                    14
towardsconversationalolap                                                                                         14
assessqueriesforinteractiveanalysisofdatacubes                                                                    14
multisensorprofilingforprecisionsoilmoisturemonitoring                                                            13
coolaframeworkforconversationalolap                                                                               11
socialbitounderstandthedebateonvaccinesonthewebandsocialmediaunravelingtheantifreeandprovaxcommunitiesinitaly      9
summarizationandvisualizationofmultilevelandmultidimensionalitemsets                                               9
augmentedbusinessintelligence                                                                                      7
dartdeanonymizationofpersonalgazetteersthroughsocialtrajectories                                                   7
supportingthegenerationofdatanarratives                                                                            6
mapmatchingonbigdataadistributedandefficientalgorithmwithahiddenmarkovmodel                                        5
optimizingexecutionplansinamultistore                                                                              5
thetelltalecube                                                                                                    4
hamletaframeworkforhumancenteredautomlviastructuredargumentation                                                   4
colossaltrajectoryminingaunifyingapproachtominebehavioralmobilitypatterns                                          3
thewhysandwhereforesofcubes                                                                                        3
suggestingassessqueriesforinteractiveanalysisofmultidimensionaldata                                                3
insightbasedvocalizationofolapsessions                                                                             3
costbasedoptimizationofmultistorequeryplans                                                                        2
olapqueryingofdocumentstoresinthepresenceofschemavariety                                                           1
asimilarityfunctionformultilevelandmultidimensionalitemsets                                                        1
conversationalolapinaction                                                                                         1
towardsaprocessdrivendesignofdataplatforms                                                                         1
explainingcubemeasuresthroughintentionalanalytics                                                                  1
conversationalolap                                                                                                 0
colossaltrajectoryminingsemanticcomovementpatternmining                                                            0
anautotuningprocessbased3dmodeltoforecastirrigationdemandinkiwifruit                                               0
autocluesexploringclusteringpipelinesviaautomlanddiversification                                                   0
automatingmaterialityassessmentwithadatadrivendocumentbasedapproach                                                0
dataplatformdesignmanagementandoptimization(dataplat)                                                              0
ontheoptimizationofqueryplansinmultistores                                                                         0
finegrainedsoilmoisturemonitoringwithpluto                                                                         0
describingandassessingcubesthroughintentionalanalytics                                                             0
describingmultidimensionaldatathroughhighlights                                                                    0
processdrivendesignofclouddataplatforms                                                                            0
streamingapproachtoschemaprofiling                                                                                 0
usingregressiontoexplaincubemeasures                                                                               0
voolamodularinsightbasedframeworkforvocalizingolapsessions                                                         0
Name: citingid, dtype: int64

In [168]:
scopus_papers = scopus[["Paper title", "Paper eid", "Paper doi", "citeid"]].drop_duplicates().sort_values(by=["Paper title"]).reset_index(drop=True)
scopus_papers

,Paper title,Paper eid,Paper doi,citeid
0,A Similarity Function for Multi-Level and Mult...,2-s2.0-85051863772,NaN,asimilarityfunctionformultilevelandmultidimens...
1,A Survey and Experimental Study on Privacy-Pre...,2-s2.0-85132525373,10.1109/TKDE.2022.3174204,asurveyandexperimentalstudyonprivacypreserving...
2,A-BI<sup>+</sup>: A framework for Augmented Bu...,2-s2.0-85082441558,10.1016/j.is.2020.101520,abiaframeworkforaugmentedbusinessintelligence
3,An auto-tuning process-based 3D model to forec...,2-s2.0-85212101165,10.1016/j.ecoinf.2024.102947,anautotuningprocessbased3dmodeltoforecastirrig...
4,Assess queries for interactive analysis of dat...,2-s2.0-85113712544,10.5441/002/edbt.2021.12,assessqueriesforinteractiveanalysisofdatacubes
5,Augmented business intelligence,2-s2.0-85062645475,NaN,augmentedbusinessintelligence
6,AutoClues: Exploring Clustering Pipelines via ...,2-s2.0-85192544367,10.1007/978-981-97-2242-6_20,autocluesexploringclusteringpipelinesviaautoml...
7,Automating materiality assessment with a data-...,2-s2.0-85213286497,10.1016/j.jjimei.2024.100310,automatingmaterialityassessmentwithadatadriven...
8,COOL: A framework for conversational OLAP,2-s2.0-85103428030,10.1016/j.is.2021.101752,coolaframeworkforconversationalolap
9,Colossal Trajectory Mining Semantic Co-movemen...,2-s2.0-85202010909,NaN,colossaltrajectoryminingsemanticcomovementpatt...
10,Colossal Trajectory Mining: A unifying approac...,2-s2.0-85174707802,10.1016/j.eswa.2023.122055,colossaltrajectoryminingaunifyingapproachtomin...
11,Conversational OLAP,2-s2.0-85118769792,NaN,conversationalolap
12,Conversational OLAP in action,2-s2.0-85113716450,10.5441/002/edbt.2021.74,conversationalolapinaction
13,Cost-based Optimization of Multistore Query Plans,2-s2.0-85139405955,10.1007/s10796-022-10320-2,costbasedoptimizationofmultistorequeryplans
14,Crop Management with the IoT: An Interdiscipli...,2-s2.0-85100942957,10.3390/agronomy11010181,cropmanagementwiththeiotaninterdisciplinarysurvey
15,DART: De-Anonymization of personal gazetteers ...,2-s2.0-85093926143,10.1016/j.jisa.2020.102634,dartdeanonymizationofpersonalgazetteersthrough...
16,"Data Platform Design, Management, and Optimiza...",2-s2.0-85158975690,NaN,dataplatformdesignmanagementandoptimization(da...
17,Describing Multidimensional Data Through Highl...,2-s2.0-85137469232,NaN,describingmultidimensionaldatathroughhighlights
18,Describing and Assessing Cubes Through Intenti...,2-s2.0-85165002810,10.48786/edbt.2023.69,describingandassessingcubesthroughintentionala...
19,Enhancing Cubes with Models to Describe Multid...,2-s2.0-85107683405,10.1007/s10796-021-10147-3,enhancingcubeswithmodelstodescribemultidimensi...
20,Explaining cube measures through Intentional A...,2-s2.0-85180538265,10.1016/j.is.2023.102338,explainingcubemeasuresthroughintentionalanalytics
21,Exploiting the Internet Resources for Autonomo...,2-s2.0-85160651880,10.3390/agriculture13051005,exploitingtheinternetresourcesforautonomousrob...
22,Fine-grained Soil Moisture Monitoring with PLUTO,2-s2.0-85173428371,NaN,finegrainedsoilmoisturemonitoringwithpluto
23,HAMLET: A framework for Human-centered AutoML ...,2-s2.0-85145965157,10.1016/j.future.2022.12.035,hamletaframeworkforhumancenteredautomlviastruc...
24,Insight-Based Vocalization of OLAP Sessions,2-s2.0-85137993971,10.1007/978-3-031-15740-0_15,insightbasedvocalizationofolapsessions
25,Making data platforms smarter with MOSES,2-s2.0-85109035166,10.1016/j.future.2021.06.031,makingdataplatformssmarterwithmoses
26,Map-matching on big data: A distributed and ef...,2-s2.0-85070329171,10.23919/MIPRO.2019.8757119,mapmatchingonbigdataadistributedandefficiental...
27,Multi-sensor profiling for precision soil-mois...,2-s2.0-85129541562,10.1016/j.compag.2022.106924,multisensorprofilingforprecisionsoilmoisturemo...
28,OLAP Querying of Document Stores in the Presen...,2-s2.0-85090883258,NaN,olapqueryingofdocumentstoresinthepresenceofsch...
29,On the Optimization of Query Plans in Multisto...,2-s2.0-85173485992,NaN,ontheoptimizationofqueryplansinmultistores
30,Optimizing Execution Plans in a Multistore,2-s2.0-85115134032,10.1007/978-3-030-82472-3_11,optimizingexecutionplansinamultistore
31,Process-driven design of cloud data platforms,2-s2.0-85216873928,10.1016/j.is.2025.102527,processdrivendesignofclouddataplatforms
32,Social BI to understand the debate on vaccines...,2-s2.0-85070525370,10.1007/s13278-019-0590-x,socialbitounderstandthedebateonvaccinesonthewe...
33,Streaming Approach to Schema Profiling,2-s2.0-85172020306,10.1007/978-3-031-42941-5_19,streamingapproachtoschemaprofiling
34,Suggesting Assess Queries for Interactive Anal...,2-s2.0-85129353199,10.1109/TKDE.2022.3171516,suggestingassessqueriesforinteractiveanalysiso...
35,Summarization and visualization of multi-level...,2-s2.0-85079239065,10.1016/j.ins.2020.02.006,summarizationandvisualizationofmultilevelandmu...
36,Supporting the generation of data narratives,2-s2.0-85095734112,NaN,supportingthegenerationofdatanarratives
37,The Tell-Tale Cube,2-s2.0-85090100247,10.1007/978-3-030-54832-2_16,thetelltalecube
38,The Whys and Wherefores of Cubes,2-s2.0-85153334849,NaN,thewhysandwhereforesofcubes
39,Towards a Conceptual Model for Data Narratives,2-s2.0-85097380415,10.1007/978-3-030-62522-1_19,towardsaconceptualmodelfordatanarratives
40,Towards a Process-Driven Design of Data Platforms,2-s2.0-85188658537,NaN,towardsaprocessdrivendesignofdataplatforms
41,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,towardsafoundationalapiforresilientdistributed...
42,Towards conversational OLAP,2-s2.0-85082444588,NaN,towardsconversationalolap
43,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,trajectorybasedspatiotemporalentitylinking
44,Using Regression to Explain Cube Measures,2-s2.0-85173478290,NaN,usingregressiontoexplaincubemeasures
45,VOOL: A modular insight-based framework for vo...,2-s2.0-85211035819,10.1016/j.is.2024.102496,voolamodularinsightbasedframeworkforvocalizing...

In [169]:
scopus_papers.groupby(by=["citeid"]).count().reset_index()

,citeid,Paper title,Paper eid,Paper doi
0,abiaframeworkforaugmentedbusinessintelligence,1,1,1
1,anautotuningprocessbased3dmodeltoforecastirrig...,1,1,1
2,asimilarityfunctionformultilevelandmultidimens...,1,1,0
3,assessqueriesforinteractiveanalysisofdatacubes,1,1,1
4,asurveyandexperimentalstudyonprivacypreserving...,1,1,1
5,augmentedbusinessintelligence,1,1,0
6,autocluesexploringclusteringpipelinesviaautoml...,1,1,1
7,automatingmaterialityassessmentwithadatadriven...,1,1,1
8,colossaltrajectoryminingaunifyingapproachtomin...,1,1,1
9,colossaltrajectoryminingsemanticcomovementpatt...,1,1,0
10,conversationalolap,1,1,0
11,conversationalolapinaction,1,1,1
12,coolaframeworkforconversationalolap,1,1,1
13,costbasedoptimizationofmultistorequeryplans,1,1,1
14,cropmanagementwiththeiotaninterdisciplinarysurvey,1,1,1
15,dartdeanonymizationofpersonalgazetteersthrough...,1,1,1
16,dataplatformdesignmanagementandoptimization(da...,1,1,0
17,describingandassessingcubesthroughintentionala...,1,1,1
18,describingmultidimensionaldatathroughhighlights,1,1,0
19,enhancingcubeswithmodelstodescribemultidimensi...,1,1,1
20,explainingcubemeasuresthroughintentionalanalytics,1,1,1
21,exploitingtheinternetresourcesforautonomousrob...,1,1,1
22,finegrainedsoilmoisturemonitoringwithpluto,1,1,0
23,hamletaframeworkforhumancenteredautomlviastruc...,1,1,1
24,insightbasedvocalizationofolapsessions,1,1,1
25,makingdataplatformssmarterwithmoses,1,1,1
26,mapmatchingonbigdataadistributedandefficiental...,1,1,1
27,multisensorprofilingforprecisionsoilmoisturemo...,1,1,1
28,olapqueryingofdocumentstoresinthepresenceofsch...,1,1,0
29,ontheoptimizationofqueryplansinmultistores,1,1,0
30,optimizingexecutionplansinamultistore,1,1,1
31,processdrivendesignofclouddataplatforms,1,1,1
32,socialbitounderstandthedebateonvaccinesonthewe...,1,1,1
33,streamingapproachtoschemaprofiling,1,1,1
34,suggestingassessqueriesforinteractiveanalysiso...,1,1,1
35,summarizationandvisualizationofmultilevelandmu...,1,1,1
36,supportingthegenerationofdatanarratives,1,1,0
37,thetelltalecube,1,1,1
38,thewhysandwhereforesofcubes,1,1,0
39,towardsaconceptualmodelfordatanarratives,1,1,1
40,towardsafoundationalapiforresilientdistributed...,1,1,1
41,towardsaprocessdrivendesignofdataplatforms,1,1,0
42,towardsconversationalolap,1,1,0
43,trajectorybasedspatiotemporalentitylinking,1,1,1
44,usingregressiontoexplaincubemeasures,1,1,0
45,voolamodularinsightbasedframeworkforvocalizing...,1,1,1

In [170]:
scopus_lookup = {}
for x in scopus_papers.to_numpy():
    scopus_lookup[x[3]] = x[:3]
scopus_lookup

{'asimilarityfunctionformultilevelandmultidimensionalitemsets': array(['A Similarity Function for Multi-Level and Multi-Dimensional Itemsets',
        '2-s2.0-85051863772', nan], dtype=object),
 'asurveyandexperimentalstudyonprivacypreservingtrajectorydatapublishing': array(['A Survey and Experimental Study on Privacy-Preserving Trajectory Data Publishing',
        '2-s2.0-85132525373', '10.1109/TKDE.2022.3174204'], dtype=object),
 'abiaframeworkforaugmentedbusinessintelligence': array(['A-BI<sup>+</sup>: A framework for Augmented Business Intelligence',
        '2-s2.0-85082441558', '10.1016/j.is.2020.101520'], dtype=object),
 'anautotuningprocessbased3dmodeltoforecastirrigationdemandinkiwifruit': array(['An auto-tuning process-based 3D model to forecast irrigation demand in kiwifruit',
        '2-s2.0-85212101165', '10.1016/j.ecoinf.2024.102947'], dtype=object),
 'assessqueriesforinteractiveanalysisofdatacubes': array(['Assess queries for interactive analysis of data cubes',
        '2-s2.0-85113712544', '10.5441/002/edbt.2021.12'], dtype=object),
 'augmentedbusinessintelligence': array(['Augmented business intelligence', '2-s2.0-85062645475', nan],
       dtype=object),
 'autocluesexploringclusteringpipelinesviaautomlanddiversification': array(['AutoClues: Exploring Clustering Pipelines via\xa0AutoML and\xa0Diversification',
        '2-s2.0-85192544367', '10.1007/978-981-97-2242-6_20'], dtype=object),
 'automatingmaterialityassessmentwithadatadrivendocumentbasedapproach': array(['Automating materiality assessment with a data-driven document-based approach',
        '2-s2.0-85213286497', '10.1016/j.jjimei.2024.100310'], dtype=object),
 'coolaframeworkforconversationalolap': array(['COOL: A framework for conversational OLAP', '2-s2.0-85103428030',
        '10.1016/j.is.2021.101752'], dtype=object),
 'colossaltrajectoryminingsemanticcomovementpatternmining': array(['Colossal Trajectory Mining Semantic Co-movement Pattern Mining',
        '2-s2.0-85202010909', nan], dtype=object),
 'colossaltrajectoryminingaunifyingapproachtominebehavioralmobilitypatterns': array(['Colossal Trajectory Mining: A unifying approach to mine behavioral mobility patterns',
        '2-s2.0-85174707802', '10.1016/j.eswa.2023.122055'], dtype=object),
 'conversationalolap': array(['Conversational OLAP', '2-s2.0-85118769792', nan], dtype=object),
 'conversationalolapinaction': array(['Conversational OLAP in action', '2-s2.0-85113716450',
        '10.5441/002/edbt.2021.74'], dtype=object),
 'costbasedoptimizationofmultistorequeryplans': array(['Cost-based Optimization of Multistore Query Plans',
        '2-s2.0-85139405955', '10.1007/s10796-022-10320-2'], dtype=object),
 'cropmanagementwiththeiotaninterdisciplinarysurvey': array(['Crop Management with the IoT: An Interdisciplinary Survey',
        '2-s2.0-85100942957', '10.3390/agronomy11010181'], dtype=object),
 'dartdeanonymizationofpersonalgazetteersthroughsocialtrajectories': array(['DART: De-Anonymization of personal gazetteers through social trajectories',
        '2-s2.0-85093926143', '10.1016/j.jisa.2020.102634'], dtype=object),
 'dataplatformdesignmanagementandoptimization(dataplat)': array(['Data Platform Design, Management, and Optimization (DATAPLAT)',
        '2-s2.0-85158975690', nan], dtype=object),
 'describingmultidimensionaldatathroughhighlights': array(['Describing Multidimensional Data Through Highlights (Discussion Paper)',
        '2-s2.0-85137469232', nan], dtype=object),
 'describingandassessingcubesthroughintentionalanalytics': array(['Describing and Assessing Cubes Through Intentional Analytics',
        '2-s2.0-85165002810', '10.48786/edbt.2023.69'], dtype=object),
 'enhancingcubeswithmodelstodescribemultidimensionaldata': array(['Enhancing Cubes with Models to Describe Multidimensional Data',
        '2-s2.0-85107683405', '10.1007/s10796-021-10147-3'], dtype=object),
 'explainingcubemeasuresthroughintentionalanalytics': array(['Explaining cube measures through Intentional Analytics',
        '2-s2.0-85180538265', '10.1016/j.is.2023.102338'], dtype=object),
 'exploitingtheinternetresourcesforautonomousrobotsinagriculture': array(['Exploiting the Internet Resources for Autonomous Robots in Agriculture',
        '2-s2.0-85160651880', '10.3390/agriculture13051005'], dtype=object),
 'finegrainedsoilmoisturemonitoringwithpluto': array(['Fine-grained Soil Moisture Monitoring with PLUTO',
        '2-s2.0-85173428371', nan], dtype=object),
 'hamletaframeworkforhumancenteredautomlviastructuredargumentation': array(['HAMLET: A framework for Human-centered AutoML via Structured Argumentation',
        '2-s2.0-85145965157', '10.1016/j.future.2022.12.035'], dtype=object),
 'insightbasedvocalizationofolapsessions': array(['Insight-Based Vocalization of\xa0OLAP Sessions',
        '2-s2.0-85137993971', '10.1007/978-3-031-15740-0_15'], dtype=object),
 'makingdataplatformssmarterwithmoses': array(['Making data platforms smarter with MOSES', '2-s2.0-85109035166',
        '10.1016/j.future.2021.06.031'], dtype=object),
 'mapmatchingonbigdataadistributedandefficientalgorithmwithahiddenmarkovmodel': array(['Map-matching on big data: A distributed and efficient algorithm with a hidden Markov model',
        '2-s2.0-85070329171', '10.23919/MIPRO.2019.8757119'], dtype=object),
 'multisensorprofilingforprecisionsoilmoisturemonitoring': array(['Multi-sensor profiling for precision soil-moisture monitoring',
        '2-s2.0-85129541562', '10.1016/j.compag.2022.106924'], dtype=object),
 'olapqueryingofdocumentstoresinthepresenceofschemavariety': array(['OLAP Querying of Document Stores in the Presence of Schema Variety',
        '2-s2.0-85090883258', nan], dtype=object),
 'ontheoptimizationofqueryplansinmultistores': array(['On the Optimization of Query Plans in Multistores (Discussion Paper)',
        '2-s2.0-85173485992', nan], dtype=object),
 'optimizingexecutionplansinamultistore': array(['Optimizing Execution Plans in a Multistore', '2-s2.0-85115134032',
        '10.1007/978-3-030-82472-3_11'], dtype=object),
 'processdrivendesignofclouddataplatforms': array(['Process-driven design of cloud data platforms',
        '2-s2.0-85216873928', '10.1016/j.is.2025.102527'], dtype=object),
 'socialbitounderstandthedebateonvaccinesonthewebandsocialmediaunravelingtheantifreeandprovaxcommunitiesinitaly': array(['Social BI to understand the debate on vaccines on the Web and social media: unraveling the anti-, free, and pro-vax communities in Italy',
        '2-s2.0-85070525370', '10.1007/s13278-019-0590-x'], dtype=object),
 'streamingapproachtoschemaprofiling': array(['Streaming Approach to\xa0Schema Profiling', '2-s2.0-85172020306',
        '10.1007/978-3-031-42941-5_19'], dtype=object),
 'suggestingassessqueriesforinteractiveanalysisofmultidimensionaldata': array(['Suggesting Assess Queries for Interactive Analysis of Multidimensional Data',
        '2-s2.0-85129353199', '10.1109/TKDE.2022.3171516'], dtype=object),
 'summarizationandvisualizationofmultilevelandmultidimensionalitemsets': array(['Summarization and visualization of multi-level and multi-dimensional itemsets',
        '2-s2.0-85079239065', '10.1016/j.ins.2020.02.006'], dtype=object),
 'supportingthegenerationofdatanarratives': array(['Supporting the generation of data narratives',
        '2-s2.0-85095734112', nan], dtype=object),
 'thetelltalecube': array(['The Tell-Tale Cube', '2-s2.0-85090100247',
        '10.1007/978-3-030-54832-2_16'], dtype=object),
 'thewhysandwhereforesofcubes': array(['The Whys and Wherefores of Cubes', '2-s2.0-85153334849', nan],
       dtype=object),
 'towardsaconceptualmodelfordatanarratives': array(['Towards a Conceptual Model for Data Narratives',
        '2-s2.0-85097380415', '10.1007/978-3-030-62522-1_19'], dtype=object),
 'towardsaprocessdrivendesignofdataplatforms': array(['Towards a Process-Driven Design of Data Platforms',
        '2-s2.0-85188658537', nan], dtype=object),
 'towardsafoundationalapiforresilientdistributedsystemsdesign': array(['Towards a foundational API for resilient distributed systems design',
        '2-s2.0-85035209468', '10.1109/FAS-W.2017.116'], dtype=object),
 'towardsconversationalolap': array(['Towards conversational OLAP', '2-s2.0-85082444588', nan],
       dtype=object),
 'trajectorybasedspatiotemporalentitylinking': array(['Trajectory-Based Spatiotemporal Entity Linking',
        '2-s2.0-85096846619', '10.1109/TKDE.2020.3036633'], dtype=object),
 'usingregressiontoexplaincubemeasures': array(['Using Regression to Explain Cube Measures', '2-s2.0-85173478290',
        nan], dtype=object),
 'voolamodularinsightbasedframeworkforvocalizingolapsessions': array(['VOOL: A modular insight-based framework for vocalizing OLAP sessions',
        '2-s2.0-85211035819', '10.1016/j.is.2024.102496'], dtype=object)}

In [171]:
scopus_unique = scopus["citeid"].sort_values().unique()
len(scopus_unique)

46

In [172]:
scholar_unique = scholar["citeid"].sort_values().unique()
len(scholar_unique)

36

In [173]:
not_cited_ids = []
for x in scholar_unique:  # for each paper in scholar
    citations_scholar = scholar[scholar["citeid"] == x]  # get its citing papers from scholar
    paper_scopus = scopus[(scopus["citeid"] == x)]  # get the paper from scopus...
    if len(paper_scopus) == 0:  # if the paper is not on scopus...
        print(x + " is not in scopus")
    else:
        for y in citations_scholar["citingid"].unique():  # for each of the citing papers from scholar
            # if (citations_scholar["Citing paper title"].str.contains('Compressione').any()): print("Here")
            if not paper_scopus["citingid"].str.contains(y).any():  # if this citation is not in scopus...
                not_cited_ids.append([x, y])  # add it
not_cited = pd.DataFrame(not_cited_ids, columns=["citeid", "citingid"])
not_cited

dynamicstreamclusteringforrealtimeschemaprofilingwithdsc is not in scopus
smartirrigationsystemforprecisionwatermanagementeffectonyieldandfruitqualityofyellowfleshedkiwifruitinnorthernitaly is not in scopus

/tmp/ipykernel_4239/635451665.py:10: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  if not paper_scopus["citingid"].str.contains(y).any():  # if this citation is not in scopus...

,citeid,citingid
0,abiaframeworkforaugmentedbusinessintelligence,lainteligenciadenegociosylaanalíticadedatosenl...
1,abiaframeworkforaugmentedbusinessintelligence,theimpactofbusinessintelligencecharacteristics...
2,abiaframeworkforaugmentedbusinessintelligence,augmentingtheknowledgepyramidwithunconventiona...
3,abiaframeworkforaugmentedbusinessintelligence,lainteligenciadenegociosylaanalíticadedatosenl...
4,abiaframeworkforaugmentedbusinessintelligence,solucióndeinteligenciadenegociosparaelaprovech...
...,...,...
187,towardsafoundationalapiforresilientdistributed...,addressingcollectivecomputationsefficiencytowa...
188,towardsconversationalolap,augmentingtheknowledgepyramidwithunconventiona...
189,trajectorybasedspatiotemporalentitylinking,augmentingtheknowledgepyramidwithunconventiona...
190,trajectorybasedspatiotemporalentitylinking,trajectoryuserlinkingviahierarchicalspatiotemp...
191,trajectorybasedspatiotemporalentitylinking,astudyonprivacyprotectiontechniquesforspatiote...

In [174]:
missing_papers = scholar[["Citing paper title", "citingid"]].drop_duplicates().merge(not_cited, on=["citingid"])
missing_papers

,Citing paper title,citingid,citeid
0,Everything you wanted to know about smart agri...,everythingyouwantedtoknowaboutsmartagriculture,cropmanagementwiththeiotaninterdisciplinarysurvey
1,Analysis of chlorophyll and carotenoids conten...,analysisofchlorophyllandcarotenoidscontentinbr...,cropmanagementwiththeiotaninterdisciplinarysurvey
2,LambdAgrIoT: a new architecture for agricultur...,lambdagriotanewarchitectureforagriculturalauto...,cropmanagementwiththeiotaninterdisciplinarysurvey
3,An Intelligent Agro-Cloud Framework For Effici...,anintelligentagrocloudframeworkforefficientcro...,cropmanagementwiththeiotaninterdisciplinarysurvey
4,A model for automatized data integration in ha...,amodelforautomatizeddataintegrationinhadoopbas...,cropmanagementwiththeiotaninterdisciplinarysurvey
...,...,...,...
203,The Impact of Business Intelligence Characteri...,theimpactofbusinessintelligencecharacteristics...,abiaframeworkforaugmentedbusinessintelligence
204,La inteligencia de negocios y la anal�tica de ...,lainteligenciadenegociosylaanal�ticadedatosenl...,abiaframeworkforaugmentedbusinessintelligence
205,Soluci�n de inteligencia de negocios para el a...,soluci�ndeinteligenciadenegociosparaelaprovech...,abiaframeworkforaugmentedbusinessintelligence
206,Understanding public perceptions of COVID-19 c...,understandingpublicperceptionsofcovid19contact...,socialbitounderstandthedebateonvaccinesonthewe...
207,Ecossistemas de big data: uma revis�o sistem�tica,ecossistemasdebigdataumarevis�osistem�tica,makingdataplatformssmarterwithmoses

In [157]:
scopus_acc = []
not_in_scopus = []
missin_papers_scopus = pd.DataFrame(scopus_acc, columns=["Citing paper title", "Citing paper eid", "Citing paper doi", "citingid"])
missin_papers_scopus

Empty DataFrame
Columns: [Citing paper title, Citing paper eid, Citing paper doi, citingid]
Index: []

In [175]:
import pybliometrics
import yaml
with open("/home/config.yml") as stream:
    config = yaml.safe_load(stream)
pybliometrics.scopus.init(config_dir=config["config_dir"])
from pybliometrics.scopus import ScopusSearch
from pybliometrics.scopus import AuthorRetrieval
import sys
import pandas as pd
import time
from random import shuffle
import re

def map_string(x):
    skip_words = [":", "'", " and ", " or ", " of ", " the ", "-"]
    x = x.lower()
    for s in skip_words:
        x = x.replace(s, " ")
    _RE_COMBINE_WHITESPACE = re.compile(r"\s+")
    x = _RE_COMBINE_WHITESPACE.sub(" ", x).strip()
    return x

xx = list(missing_papers[["Citing paper title", "citingid"]].drop_duplicates().to_numpy())
shuffle(xx)
for x in xx: #[["PUTS: Privacy-Preserving and Utility-Enhancing Framework for Trajectory Synthesization", "foo"]]:
    string = "TITLE-ABS-KEY({})".format(' AND '.join(map_string(x[0]).split(' ')))
    try:
        s = ScopusSearch(string)
        # print(string)
        # print(s.results)
        if s.results is not None and len(s.results) > 0:
            papers = [[y.title, y.eid, y.doi, x[1]] for y in s.results]
            for paper in papers:
                scopus_acc = scopus_acc + [paper]
                missin_papers_scopus = pd.DataFrame(scopus_acc, columns=["Citing paper title", "Citing paper eid", "Citing paper doi", "citingid"]).drop_duplicates()
        else:
            not_in_scopus = not_in_scopus + [x[0]]
        time.sleep(1)
    except Exception as e:
        print(x[0] + " " + string + ": " + str(e) + "\n")

of OLAP Sessions. In: Chiusano, S., Cerquitelli, T., Wrembel, R.(eds) Advances in Databases and Information Systems. ADBIS 2022. Lecture Notes in Computer … TITLE-ABS-KEY(of AND olap AND sessions. AND in AND chiusano, AND s., AND cerquitelli, AND t., AND wrembel, AND r.(eds) AND advances AND in AND databases AND information AND systems. AND adbis AND 2022. AND lecture AND notes AND in AND computer AND …): Error translating query

Mod�liser la d�marche du data journaliste TITLE-ABS-KEY(mod�liser AND la AND d�marche AND du AND data AND journaliste): Error translating query

Understanding public perceptions of COVID-19 contact tracing apps: Artificial intelligence�enabled social media analysis TITLE-ABS-KEY(understanding AND public AND perceptions AND covid AND 19 AND contact AND tracing AND apps AND artificial AND intelligence�enabled AND social AND media AND analysis): Error translating query

Soluci�n de inteligencia de negocios para el aprovechamiento de los datos del servicio m�dico en una entidad bancaria TITLE-ABS-KEY(soluci�n AND de AND inteligencia AND de AND negocios AND para AND el AND aprovechamiento AND de AND los AND datos AND del AND servicio AND m�dico AND en AND una AND entidad AND bancaria): Error translating query

Fouille de s�quences de mobilit� s�mantique: sur l'�laboration de mesures pour la comparaison, l'analyse et la d�couverte de comportements TITLE-ABS-KEY(fouille AND de AND s�quences AND de AND mobilit� AND s�mantique AND sur AND l AND �laboration AND de AND mesures AND pour AND la AND comparaison, AND l AND analyse AND et AND la AND d�couverte AND de AND comportements): Error translating query

La inteligencia de negocios y la anal�tica de datos en los procesos empresariales TITLE-ABS-KEY(la AND inteligencia AND de AND negocios AND y AND la AND anal�tica AND de AND datos AND en AND los AND procesos AND empresariales): Error translating query

The Impact of Business Intelligence Characteristics on Competitiveness of Companies with the Mediating Role of Entrepreneurship, Market Orientation and Business � TITLE-ABS-KEY(the AND impact AND business AND intelligence AND characteristics AND on AND competitiveness AND companies AND with AND mediating AND role AND entrepreneurship, AND market AND orientation AND business AND �): Error translating query

Un mod�le conceptual de narration de donn�es TITLE-ABS-KEY(un AND mod�le AND conceptual AND de AND narration AND de AND donn�es): Error translating query

La inteligencia de negocios y la anal�tica de datos en los procesos empresariales Business intelligence and data analytics in business processes TITLE-ABS-KEY(la AND inteligencia AND de AND negocios AND y AND la AND anal�tica AND de AND datos AND en AND los AND procesos AND empresariales AND business AND intelligence AND data AND analytics AND in AND business AND processes): Error translating query

Ecossistemas de big data: uma revis�o sistem�tica TITLE-ABS-KEY(ecossistemas AND de AND big AND data AND uma AND revis�o AND sistem�tica): Error translating query

In [176]:
not_in_scopus

['تحليل قصص الحروب والنزاعات المسلحة المدفوعة بالبيانات-دراسة مقارنة بين المواقع العربية والأجنبية\u200e',
 'Augmenting the Knowledge Pyramid with Unconventional Data and Advanced Analytics',
 'Soil analysis with machine-learning-based processing of stepped-frequency GPR field measurements: Preliminary study',
 'Ciclo de vida de data warehouse baseado em NoSQL: adaptações e análise de desempenho de arquiteturas',
 'Business Intelligence: towards on-demand ETL over document stores',
 'Faster Access Of Credit Cards Through Data Cube Technology',
 'INTEGRATION OF MACHINE LEARNING TECHNIQUES IN DETERMINING TOMATO RIPENESS: A LITERATURE REVIEW',
 'تاثیر ویژگی\u200cهای هوش\u200cتجاری بر رقابت\u200cپذیری شرکت\u200cها با نقش میانجی کارآفرینی محوری، بازارمحوری و نوآوری در کسب\u200cوکار\u200e',
 'The Influence of Whatsapp Social Media, Parental Supervision, and Youth and Adolescent Lifestyles on Drug and Addictive Substance Use in Manado City',
 '. and Stefano Rizzi () D ID DISI-University of Bologna, Bologna, Italy {m. francia, enrico. gallinucci, matteo. golfarelli, stefano. rizzi}@ unibo. it',
 'The Adoption of the Internet of Things for SMART Agriculture in Zimbabwe',
 'Fouille de séquences de mobilité sémantique',
 'Assessing Soil Water Dynamics in a Drip-Irrigated Grapefruit Orchard Using the HYDRUS 2D/3D Model: A Comparison of Unimodal and Bimodal Hydraulic Functions',
 'A model for automatized data integration in hadoop-based data lakes',
 'A Python Package to Detect Anti-Vaccine Users on Twitter',
 'Distributed and Decentralized Algorithms for Functional Programmable Matter',
 'A Conceptual Model for Data Storytelling Highlights in Business Intelligence Environments',
 'Evolving map matching with markov decision processes',
 'P18-An IoT electronic fence for agri-robots',
 'Opportunities and Challenges for AI-supported Business Intelligence Systems–A Delphi Study',
 'A conceptual model for data storytelling highlights in business intelligence environments',
 'DPTraj-PM: Differentially Private Trajectory Synthesis Using Prefix Tree and Markov Process',
 'Precision Farming and Protected Cultivation in Digital Era',
 'A Privacy-Preserving Trajectory Synthesis Method Based on Vector Translation Invariance Supporting Traffic Constraints',
 'BEYOND DASHBOARDS? DESIGNING DATA STORIES FOR EFFECTIVE USE IN BUSINESS INTELLIGENCE AND ANALYTICS',
 'طراحی مدل هستی\u200cشناسی کسب\u200cوکار شرکت سنگ آهن بر مبنای مدل\u200cهای داده\u200cای وب معنایی\u200e',
 'Optimisation and interactive data analysis: the Traveling Analyst Problem',
 'Connecting the Dots: Refugee Data Narratives',
 'On Reasoning About Black-Box Udfs by Classifying their Performance Characteristics',
 "Vers une aide intelligible à l'analyse prédictive",
 'Designing the Business Ontology of Ehya Iron Company based on Semantic Web Data Models',
 'The Role of Ideology in Motivating Lone Actor Terrorism: An Analysis of the Online Record of the Christchurch Terrorist',
 'An extensive survey of smart agriculture technologies: Current security posture',
 'THE ADOPTION OF THE INTERNET OF THINGS FOR SMART AGRICULTURE IN ZIMBABWE',
 'METADATA MANAGEMENT FRAMEWORK FOR BI-DRIVEN DATA LAKES',
 'Ecossistemas de big data: uma revisão sistemática',
 'Analysis of war data-driven stories-A comparative study between Arabian and foreign websites',
 '都市農業地域のスマート農業技術ニーズの評価 東京都内における比較分析',
 'Beyond dashboards? designing data stories for effective use in business intelligence and analytics',
 'İŞLETMECİLİK, PAZARLAMA VE KÜLTÜR PERSPEKTİFİNDEN TURİZM',
 'PROGETTAZIONE E PROTOTIPAZIONE DI UN FRAMEWORK PER CONVERSATIONAL OLAP',
 'Automated data processing and feature engineering for deep learning and big data applications: a survey',
 'Serviz: A Visual Analytics System for the Analysis of Sequential Rules and its Application to Airport Ground Handling Operations',
 'Differentially Private Synthetic Data Generation Of Data Collected Over Time',
 'Generalization of deep learning models applied to semantic segmentation of in-field natural images in vineyards',
 "Parents' Decisions to Vaccinate Children against COVID-19: A Scoping Review. Vaccines 2021, 9, 1476",
 'Concepts towards an automated data pre-processing and preparation within data lakes',
 'Towards Privacy Preservation using Clustering based Anonymization: Recent Advances and Future Research Outlook',
 'SeRViz: an interactive visualization framework for the analysis of sequential rules and frequent itemsets',
 'Modéliser la démarche du data journaliste',
 'Un modèle conceptual de narration de données',
 'SoK: Can Trajectory Generation Combine Privacy and Utility?',
 'An Intelligent Agro-Cloud Framework For Efficient Crop Cultivation',
 'Designing a Star Schema for Optimizing the Total Sales of Motorcycles',
 'Progettazione di una piattaforma web per la simulazione di programmi aggregati',
 "Système d'information décisionnel, de la narration à la simulation: application à la surveillance épidémiologique de la tuberculose au Gabon",
 'A Path Model of the Intention to Adopt Variable Rate Irrigation in Northeast Italy. Sustainability 2021, 13, 1879',
 'The Impact of Business Intelligence Characteristics on Competitiveness of Companies with the Mediating Role of Entrepreneurship, Market Orientation and Business …',
 'Deep learning for trajectory data management and mining: A survey and beyond',
 'Design and Implementation of a Data Platform for Stream Analysis: WeLASER as a Case Study',
 'تاثیر ویژگیهای هوشتجاری بر رقابتپذیری شرکتها با نقش میانجی کارآفرینی محوری، بازارمحوری و نوآوری در کسبوکار',
 "Fouille de séquences de mobilité sémantique: sur l'élaboration de mesures pour la comparaison, l'analyse et la découverte de comportements",
 'Enterprise Data Warehouse Based on Data Vault 2.0 Sourced by a Data Lake: A Banking Industry use Case',
 'Dynamic Stream Clustering for Real-Time Schema Profiling with Dsc+',
 'An intelligent agro-cloud framework for efficient crop cultivation',
 'Software Architecture for Agricultural Robots: Systems, Requirements, Challenges, Case Studies, and Future Perspectives',
 'Potential and Trends of IoT Application in Agriculture in Vietnam',
 'The adoption of the Internet of Things for smart agriculture in Zimbabwe',
 'Использование колоночных СУБД для формирования многомерных структур данных',
 'Ciclo de Vida de Data Warehouse baseado em NoSQL: Adaptações e Análise de Desempenho de Arquiteturas',
 'Everything you wanted to know about smart agriculture',
 'Compressione e Vocalizzazione di Risultati Multidimensionali nel Paradigma OLAP',
 'Beyond Dashboards? Designing Data Stories for Effective Use in Business Intelligence and Analytics',
 'Check for updates A Perception Skill for Herding with a 4-Legged Robot',
 "Leveraging users' behavior, intentions and interests for enhancing Exploratory Data Analysis and Data Narration",
 'Business Intelligence: vers un ETL à la demande sur des bases de données orientées documents',
 'Towards Efficient and Secure Intelligent Transportation Services: AI-driven Traffic Light Controller and Privacy-Preserving Mobility Data Generation',
 'Optimisation et analyse interactive de données: le Problème du Voyageur de Données',
 "Parents' decisions to vaccinate children against COVID-19: a scoping review. Vaccines 2021; 9: 1476",
 'PrivStream: An Algorithm for Streaming Differentially Private Data',
 'Solución de inteligencia de negocios para el aprovechamiento de los datos del servicio médico en una entidad bancaria',
 'Persamaan linier Tinggi Bukaan Pintu Air Terhadap Kecepatan Aliran dengan Kedalaman Basah di saluran irigasi berbasis IoT Desa Sukoanyar',
 'Business Intelligence: vers un ETL à la demande sur des bases de données orientées documents']

In [177]:
missin_papers_scopus

,Citing paper title,Citing paper eid,Citing paper doi,citingid
0,LDPTrace: Locally Differentially Private Traje...,2-s2.0-85153584578,10.14778/3594512.3594520,ldptracelocallydifferentiallyprivatetrajectory...
1,Understanding public perceptions of COVID-19 c...,2-s2.0-85106469791,10.2196/26618,understandingpublicperceptionsofcovid19contact...
2,Parents’ intention to vaccinate their children...,2-s2.0-85199260826,10.57643/lsadj.2024.27.1_02,parentsdecisionstovaccinatechildrenagainstcovi...
3,Parents’ decisions to vaccinate children again...,2-s2.0-85121534481,10.3390/vaccines9121476,parentsdecisionstovaccinatechildrenagainstcovi...
4,LambdAgrIoT: a new architecture for agricultur...,2-s2.0-85140242438,10.1007/s10586-022-03592-5,lambdagriotanewarchitectureforagriculturalauto...
...,...,...,...,...
17052,Exploring presenteeism among hospital physicia...,2-s2.0-85073935757,10.1108/QROM-11-2018-1699,aframeworkforcraftingdatanarratives
17053,"Crafting ""integrity"": The implications of auth...",2-s2.0-85091693226,10.4000/samaj.6414,aframeworkforcraftingdatanarratives
17054,Transforming Transcripts Into Stories: A Multi...,2-s2.0-85067358102,10.1177/1609406919856797,aframeworkforcraftingdatanarratives
17055,Preparing effective history teachers: The asse...,2-s2.0-84880403835,10.1016/j.jssr.2013.04.005,aframeworkforcraftingdatanarratives
17056,Crafting an agentive self: Case studies of dig...,2-s2.0-33749634616,10.58680/rte20065995,aframeworkforcraftingdatanarratives

In [178]:
def filter_col(df):
    df = df[[x for x in df.columns if x != "citingid" and x != "citeid" and "doi" not in x]]
    df = df.rename({"Paper title": "Cited paper title", "Paper eid": "Cited paper eid"}, axis=1)
    df["Cited paper link"] = df["Cited paper eid"].apply(lambda x: "https://www.scopus.com/record/display.uri?eid={}&origin=resultslist".format(x))
    df["Citing paper link"] = df["Citing paper eid"].apply(lambda x: "https://www.scopus.com/record/display.uri?eid={}&origin=resultslist".format(x))
    return df

In [179]:
filter_col(scopus_papers.merge(not_cited, on=["citeid"]).merge(missin_papers_scopus, on=["citingid"])).sort_values(by=['Cited paper title', 'Citing paper title']).to_csv('/home/data/missing-{}-all.csv'.format(time.time()), index=False)
filter_col(scopus_papers.merge(not_cited, on=["citeid"]).merge(missin_papers_scopus[missin_papers_scopus["citingid"] == missin_papers_scopus["Citing paper title"].apply(lambda x: map_id(x))], on=["citingid"])).sort_values(by=['Cited paper title', 'Citing paper title']).to_csv('/home/data/missing-{}-red.csv'.format(time.time()), index=False)