In [2]:
import pybliometrics
print(pybliometrics.__version__)
pybliometrics.scopus.init()
import yaml
from pybliometrics.scopus import ScopusSearch
from pybliometrics.scopus.utils import *
from pybliometrics.scopus import AuthorRetrieval
import sys
import time

with open("/home/config.yml") as stream:
    config = yaml.safe_load(stream)

create_config(keys=[config["SCOPUS-KEY"]])

s = ScopusSearch("AU-ID(56344636600)")
my_papers = s.results
my_papers = [[x.title, x.eid, x.doi] for x in my_papers if x.eid not in ["2-s2.0-84906819575", "2-s2.0-84976641685"]]
my_papers

4.1
Creating config file at /root/.config/pybliometrics.cfg with default paths...
Configuration file successfully created at /root/.config/pybliometrics.cfg
For details see https://pybliometrics.rtfd.io/en/stable/configuration.html.

[['Process-driven design of cloud data platforms',
  '2-s2.0-85216873928',
  '10.1016/j.is.2025.102527'],
 ['Automating materiality assessment with a data-driven document-based approach',
  '2-s2.0-85213286497',
  '10.1016/j.jjimei.2024.100310'],
 ['An auto-tuning process-based 3D model to forecast irrigation demand in kiwifruit',
  '2-s2.0-85212101165',
  '10.1016/j.ecoinf.2024.102947'],
 ['VOOL: A modular insight-based framework for vocalizing OLAP sessions',
  '2-s2.0-85211035819',
  '10.1016/j.is.2024.102496'],
 ['Colossal Trajectory Mining: A unifying approach to mine behavioral mobility patterns',
  '2-s2.0-85174707802',
  '10.1016/j.eswa.2023.122055'],
 ['Explaining cube measures through Intentional Analytics',
  '2-s2.0-85180538265',
  '10.1016/j.is.2023.102338'],
 ['Colossal Trajectory Mining Semantic Co-movement Pattern Mining',
  '2-s2.0-85202010909',
  None],
 ['AutoClues: Exploring Clustering Pipelines via\xa0AutoML and\xa0Diversification',
  '2-s2.0-85192544367',
  '10.1007/978-981-97-2242-6_20'],
 ['Towards a Process-Driven Design of Data Platforms',
  '2-s2.0-85188658537',
  None],
 ['Cost-based Optimization of Multistore Query Plans',
  '2-s2.0-85139405955',
  '10.1007/s10796-022-10320-2'],
 ['A Survey and Experimental Study on Privacy-Preserving Trajectory Data Publishing',
  '2-s2.0-85132525373',
  '10.1109/TKDE.2022.3174204'],
 ['Suggesting Assess Queries for Interactive Analysis of Multidimensional Data',
  '2-s2.0-85129353199',
  '10.1109/TKDE.2022.3171516'],
 ['Exploiting the Internet Resources for Autonomous Robots in Agriculture',
  '2-s2.0-85160651880',
  '10.3390/agriculture13051005'],
 ['HAMLET: A framework for Human-centered AutoML via Structured Argumentation',
  '2-s2.0-85145965157',
  '10.1016/j.future.2022.12.035'],
 ['Describing and Assessing Cubes Through Intentional Analytics',
  '2-s2.0-85165002810',
  '10.48786/edbt.2023.69'],
 ['On the Optimization of Query Plans in Multistores (Discussion Paper)',
  '2-s2.0-85173485992',
  None],
 ['Using Regression to Explain Cube Measures', '2-s2.0-85173478290', None],
 ['Fine-grained Soil Moisture Monitoring with PLUTO',
  '2-s2.0-85173428371',
  None],
 ['Streaming Approach to\xa0Schema Profiling',
  '2-s2.0-85172020306',
  '10.1007/978-3-031-42941-5_19'],
 ['Data Platform Design, Management, and Optimization (DATAPLAT)',
  '2-s2.0-85158975690',
  None],
 ['The Whys and Wherefores of Cubes', '2-s2.0-85153334849', None],
 ['Trajectory-Based Spatiotemporal Entity Linking',
  '2-s2.0-85096846619',
  '10.1109/TKDE.2020.3036633'],
 ['Multi-sensor profiling for precision soil-moisture monitoring',
  '2-s2.0-85129541562',
  '10.1016/j.compag.2022.106924'],
 ['Enhancing Cubes with Models to Describe Multidimensional Data',
  '2-s2.0-85107683405',
  '10.1007/s10796-021-10147-3'],
 ['COOL: A framework for conversational OLAP',
  '2-s2.0-85103428030',
  '10.1016/j.is.2021.101752'],
 ['Insight-Based Vocalization of\xa0OLAP Sessions',
  '2-s2.0-85137993971',
  '10.1007/978-3-031-15740-0_15'],
 ['Describing Multidimensional Data Through Highlights (Discussion Paper)',
  '2-s2.0-85137469232',
  None],
 ['Making data platforms smarter with MOSES',
  '2-s2.0-85109035166',
  '10.1016/j.future.2021.06.031'],
 ['Conversational OLAP', '2-s2.0-85118769792', None],
 ['Optimizing Execution Plans in a Multistore',
  '2-s2.0-85115134032',
  '10.1007/978-3-030-82472-3_11'],
 ['Conversational OLAP in action',
  '2-s2.0-85113716450',
  '10.5441/002/edbt.2021.74'],
 ['Assess queries for interactive analysis of data cubes',
  '2-s2.0-85113712544',
  '10.5441/002/edbt.2021.12'],
 ['Crop Management with the IoT: An Interdisciplinary Survey',
  '2-s2.0-85100942957',
  '10.3390/agronomy11010181'],
 ['DART: De-Anonymization of personal gazetteers through social trajectories',
  '2-s2.0-85093926143',
  '10.1016/j.jisa.2020.102634'],
 ['A-BI<sup>+</sup>: A framework for Augmented Business Intelligence',
  '2-s2.0-85082441558',
  '10.1016/j.is.2020.101520'],
 ['Summarization and visualization of multi-level and multi-dimensional itemsets',
  '2-s2.0-85079239065',
  '10.1016/j.ins.2020.02.006'],
 ['Towards a Conceptual Model for Data Narratives',
  '2-s2.0-85097380415',
  '10.1007/978-3-030-62522-1_19'],
 ['Supporting the generation of data narratives', '2-s2.0-85095734112', None],
 ['OLAP Querying of Document Stores in the Presence of Schema Variety',
  '2-s2.0-85090883258',
  None],
 ['The Tell-Tale Cube', '2-s2.0-85090100247', '10.1007/978-3-030-54832-2_16'],
 ['Towards conversational OLAP', '2-s2.0-85082444588', None],
 ['Social BI to understand the debate on vaccines on the Web and social media: unraveling the anti-, free, and pro-vax communities in Italy',
  '2-s2.0-85070525370',
  '10.1007/s13278-019-0590-x'],
 ['Map-matching on big data: A distributed and efficient algorithm with a hidden Markov model',
  '2-s2.0-85070329171',
  '10.23919/MIPRO.2019.8757119'],
 ['Augmented business intelligence', '2-s2.0-85062645475', None],
 ['A Similarity Function for Multi-Level and Multi-Dimensional Itemsets',
  '2-s2.0-85051863772',
  None],
 ['Towards a foundational API for resilient distributed systems design',
  '2-s2.0-85035209468',
  '10.1109/FAS-W.2017.116']]

In [3]:
import pandas as pd

dfp = pd.DataFrame(my_papers, columns=["Paper title", "Paper eid", "Paper doi"])
dfp.sort_values(["Paper title"], ignore_index=True)

,Paper title,Paper eid,Paper doi
0,A Similarity Function for Multi-Level and Mult...,2-s2.0-85051863772,None
1,A Survey and Experimental Study on Privacy-Pre...,2-s2.0-85132525373,10.1109/TKDE.2022.3174204
2,A-BI<sup>+</sup>: A framework for Augmented Bu...,2-s2.0-85082441558,10.1016/j.is.2020.101520
3,An auto-tuning process-based 3D model to forec...,2-s2.0-85212101165,10.1016/j.ecoinf.2024.102947
4,Assess queries for interactive analysis of dat...,2-s2.0-85113712544,10.5441/002/edbt.2021.12
5,Augmented business intelligence,2-s2.0-85062645475,None
6,AutoClues: Exploring Clustering Pipelines via ...,2-s2.0-85192544367,10.1007/978-981-97-2242-6_20
7,Automating materiality assessment with a data-...,2-s2.0-85213286497,10.1016/j.jjimei.2024.100310
8,COOL: A framework for conversational OLAP,2-s2.0-85103428030,10.1016/j.is.2021.101752
9,Colossal Trajectory Mining Semantic Co-movemen...,2-s2.0-85202010909,None
10,Colossal Trajectory Mining: A unifying approac...,2-s2.0-85174707802,10.1016/j.eswa.2023.122055
11,Conversational OLAP,2-s2.0-85118769792,None
12,Conversational OLAP in action,2-s2.0-85113716450,10.5441/002/edbt.2021.74
13,Cost-based Optimization of Multistore Query Plans,2-s2.0-85139405955,10.1007/s10796-022-10320-2
14,Crop Management with the IoT: An Interdiscipli...,2-s2.0-85100942957,10.3390/agronomy11010181
15,DART: De-Anonymization of personal gazetteers ...,2-s2.0-85093926143,10.1016/j.jisa.2020.102634
16,"Data Platform Design, Management, and Optimiza...",2-s2.0-85158975690,None
17,Describing Multidimensional Data Through Highl...,2-s2.0-85137469232,None
18,Describing and Assessing Cubes Through Intenti...,2-s2.0-85165002810,10.48786/edbt.2023.69
19,Enhancing Cubes with Models to Describe Multid...,2-s2.0-85107683405,10.1007/s10796-021-10147-3
20,Explaining cube measures through Intentional A...,2-s2.0-85180538265,10.1016/j.is.2023.102338
21,Exploiting the Internet Resources for Autonomo...,2-s2.0-85160651880,10.3390/agriculture13051005
22,Fine-grained Soil Moisture Monitoring with PLUTO,2-s2.0-85173428371,None
23,HAMLET: A framework for Human-centered AutoML ...,2-s2.0-85145965157,10.1016/j.future.2022.12.035
24,Insight-Based Vocalization of OLAP Sessions,2-s2.0-85137993971,10.1007/978-3-031-15740-0_15
25,Making data platforms smarter with MOSES,2-s2.0-85109035166,10.1016/j.future.2021.06.031
26,Map-matching on big data: A distributed and ef...,2-s2.0-85070329171,10.23919/MIPRO.2019.8757119
27,Multi-sensor profiling for precision soil-mois...,2-s2.0-85129541562,10.1016/j.compag.2022.106924
28,OLAP Querying of Document Stores in the Presen...,2-s2.0-85090883258,None
29,On the Optimization of Query Plans in Multisto...,2-s2.0-85173485992,None
30,Optimizing Execution Plans in a Multistore,2-s2.0-85115134032,10.1007/978-3-030-82472-3_11
31,Process-driven design of cloud data platforms,2-s2.0-85216873928,10.1016/j.is.2025.102527
32,Social BI to understand the debate on vaccines...,2-s2.0-85070525370,10.1007/s13278-019-0590-x
33,Streaming Approach to Schema Profiling,2-s2.0-85172020306,10.1007/978-3-031-42941-5_19
34,Suggesting Assess Queries for Interactive Anal...,2-s2.0-85129353199,10.1109/TKDE.2022.3171516
35,Summarization and visualization of multi-level...,2-s2.0-85079239065,10.1016/j.ins.2020.02.006
36,Supporting the generation of data narratives,2-s2.0-85095734112,None
37,The Tell-Tale Cube,2-s2.0-85090100247,10.1007/978-3-030-54832-2_16
38,The Whys and Wherefores of Cubes,2-s2.0-85153334849,None
39,Towards a Conceptual Model for Data Narratives,2-s2.0-85097380415,10.1007/978-3-030-62522-1_19
40,Towards a Process-Driven Design of Data Platforms,2-s2.0-85188658537,None
41,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116
42,Towards conversational OLAP,2-s2.0-85082444588,None
43,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633
44,Using Regression to Explain Cube Measures,2-s2.0-85173478290,None
45,VOOL: A modular insight-based framework for vo...,2-s2.0-85211035819,10.1016/j.is.2024.102496

In [4]:
acc = []
for paper in my_papers:
    q = f"REF({paper[1]})"
    s = ScopusSearch(q, refresh=0)
    print(s)
    res = s.results
    if res is not None and len(res) > 0:
        for x in res:
            acc = acc + [paper + [x.title, x.eid, x.doi]]
    else:
        acc = acc + [paper + ["", "", ""]]

Search 'REF(2-s2.0-85216873928)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85213286497)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85212101165)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85211035819)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85174707802)' yielded 3 documents as of 2025-02-24:
    2-s2.0-85190319631
    2-s2.0-85208624461
    2-s2.0-85202010909
Search 'REF(2-s2.0-85180538265)' yielded 1 document as of 2025-02-24:
    2-s2.0-85211035819
Search 'REF(2-s2.0-85202010909)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85192544367)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85188658537)' yielded 1 document as of 2025-02-24:
    2-s2.0-85216873928
Search 'REF(2-s2.0-85139405955)' yielded 2 documents as of 2025-02-24:
    2-s2.0-85196759800
    2-s2.0-85188586018
Search 'REF(2-s2.0-85132525373)' yielded 40 documents as of 2025-02-24:
    2-s2.0-85217245348
    2-s2.0-85208497662
    2-s2.0-85214416627
    2-s2.0-85211248262
    2-s2.0-85207919389
    2-s2.0-85211771055
    2-s2.0-85209239146
    2-s2.0-85194350916
    2-s2.0-85205305848
    2-s2.0-85206889151
    2-s2.0-85199898896
    2-s2.0-85188906155
    2-s2.0-85190104979
    2-s2.0-85174857113
    2-s2.0-85179801568
    2-s2.0-85174707802
    2-s2.0-85189528150
    2-s2.0-85184080776
    2-s2.0-85214795893
    2-s2.0-85214525838
    2-s2.0-85209377036
    2-s2.0-85202010909
    2-s2.0-85199039866
    2-s2.0-85198848904
    2-s2.0-85185324120
    2-s2.0-85183974976
    2-s2.0-85177058760
    2-s2.0-85167802153
    2-s2.0-85162871531
    2-s2.0-85179892785
    2-s2.0-85145256040
    2-s2.0-85151097067
    2-s2.0-85181173731
    2-s2.0-85174704562
    2-s2.0-85144019298
    2-s2.0-85138804472
    2-s2.0-85136425113
    2-s2.0-85136226665
    2-s2.0-85110326989
    2-s2.0-85121922321
Search 'REF(2-s2.0-85129353199)' yielded 3 documents as of 2025-02-24:
    2-s2.0-85211035819
    2-s2.0-85180538265
    2-s2.0-85153334849
Search 'REF(2-s2.0-85160651880)' yielded 14 documents as of 2025-02-24:
    2-s2.0-85210579307
    2-s2.0-85188175446
    2-s2.0-85202652900
    2-s2.0-85189980784
    2-s2.0-85194170579
    2-s2.0-85189024970
    2-s2.0-85213071438
    2-s2.0-85204610597
    2-s2.0-85203491921
    2-s2.0-85193285450
    2-s2.0-85189899989
    2-s2.0-85183395253
    2-s2.0-85180699125
    2-s2.0-85180469070
Search 'REF(2-s2.0-85145965157)' yielded 4 documents as of 2025-02-24:
    2-s2.0-85189622290
    2-s2.0-85192544367
    2-s2.0-85191174113
    2-s2.0-85180065616
Search 'REF(2-s2.0-85165002810)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85173485992)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85173478290)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85173428371)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85172020306)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85158975690)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85153334849)' yielded 3 documents as of 2025-02-24:
    2-s2.0-85211035819
    2-s2.0-85180538265
    2-s2.0-85173478290
Search 'REF(2-s2.0-85096846619)' yielded 15 documents as of 2025-02-24:
    2-s2.0-85214117771
    2-s2.0-85190360494
    2-s2.0-85174857113
    2-s2.0-85174707802
    2-s2.0-85200487230
    2-s2.0-85197297885
    2-s2.0-85149039992
    2-s2.0-85132525373
    2-s2.0-85137576224
    2-s2.0-85123164859
    2-s2.0-85096846619
    2-s2.0-85132711904
    2-s2.0-85137872696
    2-s2.0-85136425113
    2-s2.0-85121922321
Search 'REF(2-s2.0-85129541562)' yielded 13 documents as of 2025-02-24:
    2-s2.0-85216873928
    2-s2.0-85212101165
    2-s2.0-85194397904
    2-s2.0-85176949684
    2-s2.0-85206183730
    2-s2.0-85203826924
    2-s2.0-85188658537
    2-s2.0-85180497388
    2-s2.0-85166665907
    2-s2.0-85166187482
    2-s2.0-85153035011
    2-s2.0-85153930157
    2-s2.0-85173428371
Search 'REF(2-s2.0-85107683405)' yielded 15 documents as of 2025-02-24:
    2-s2.0-85211035819
    2-s2.0-85210151391
    2-s2.0-85188815289
    2-s2.0-85198085340
    2-s2.0-85188808893
    2-s2.0-85180538265
    2-s2.0-85129353199
    2-s2.0-85160881368
    2-s2.0-85165002810
    2-s2.0-85173478290
    2-s2.0-85153354053
    2-s2.0-85153334849
    2-s2.0-85125529748
    2-s2.0-85137993971
    2-s2.0-85137469232
Search 'REF(2-s2.0-85103428030)' yielded 11 documents as of 2025-02-24:
    2-s2.0-85180538265
    2-s2.0-85171481610
    2-s2.0-85208021175
    2-s2.0-85165494524
    2-s2.0-85129353199
    2-s2.0-85145965157
    2-s2.0-85166634616
    2-s2.0-85153334849
    2-s2.0-85137993971
    2-s2.0-85137469232
    2-s2.0-85118769792
Search 'REF(2-s2.0-85137993971)' yielded 3 documents as of 2025-02-24:
    2-s2.0-85211035819
    2-s2.0-85197395708
    2-s2.0-85179558569
Search 'REF(2-s2.0-85137469232)' yielded 0 documents as of 2025-02-24
Search 'REF(2-s2.0-85109035166)' yielded 837 documents as of 2025-02-24:
    2-s2.0-85216873928
    2-s2.0-85187119784
    2-s2.0-85198321986
    2-s2.0-85192672282
    2-s2.0-85212543991
    2-s2.0-85206600855
    2-s2.0-85198524930
    2-s2.0-85188658537
    2-s2.0-85139405955
    2-s2.0-85160651880
    2-s2.0-85145965157
    2-s2.0-85145253028
    2-s2.0-85156237376
    2-s2.0-85156194418
    2-s2.0-85139624136
    2-s2.0-85153398298
    2-s2.0-85153352002
    2-s2.0-85153344667
    2-s2.0-85150993348
    2-s2.0-85148989374
    2-s2.0-85146689759
    2-s2.0-85150159695
    2-s2.0-85146302990
    2-s2.0-85179869417
    2-s2.0-85179868790
    2-s2.0-85179868172
    2-s2.0-85179867216
    2-s2.0-85179866197
    2-s2.0-85179866013
    2-s2.0-85179865374
    2-s2.0-85179864432
    2-s2.0-85179862728
    2-s2.0-85179861139
    2-s2.0-85174988641
    2-s2.0-85174988455
    2-s2.0-85174986436
    2-s2.0-85174986295
    2-s2.0-85174986148
    2-s2.0-85173574332
    2-s2.0-85173573199
    2-s2.0-85173568239
    2-s2.0-85173565367
    2-s2.0-85173563539
    2-s2.0-85173562487
    2-s2.0-85173561506
    2-s2.0-85173560581
    2-s2.0-85173558554
    2-s2.0-85173558089
    2-s2.0-85173485992
    2-s2.0-85173047462
    2-s2.0-85172029203
    2-s2.0-85171466328
    2-s2.0-85168580865
    2-s2.0-85165605376
    2-s2.0-85164964815
    2-s2.0-85164271095
    2-s2.0-85164269892
    2-s2.0-85164269254
    2-s2.0-85164269246
    2-s2.0-85164264339
    2-s2.0-85164262525
    2-s2.0-85164260708
    2-s2.0-85164258345
    2-s2.0-85164255117
    2-s2.0-85164255112
    2-s2.0-85164254491
    2-s2.0-85164253305
    2-s2.0-85164251729
    2-s2.0-85164251465
    2-s2.0-85164037201
    2-s2.0-85164031783
    2-s2.0-85164029789
    2-s2.0-85164029332
    2-s2.0-85164028471
    2-s2.0-85164022545
    2-s2.0-85164011116
    2-s2.0-85164010759
    2-s2.0-85164008980
    2-s2.0-85164008552
    2-s2.0-85164006624
    2-s2.0-85164002394
    2-s2.0-85163999252
    2-s2.0-85163997722
    2-s2.0-85163992184
    2-s2.0-85163991379
    2-s2.0-85163990123
    2-s2.0-85163988618
    2-s2.0-85163976669
    2-s2.0-85163974930
    2-s2.0-85163968597
    2-s2.0-85163954153
    2-s2.0-85163953209
    2-s2.0-85163942745
    2-s2.0-85163934672
    2-s2.0-85163931271
    2-s2.0-85163931063
    2-s2.0-85163927170
    2-s2.0-85163778388
    2-s2.0-85163728155
    2-s2.0-85163712536
    2-s2.0-85163704264
    2-s2.0-85163700512
    2-s2.0-85163693636
    2-s2.0-85163671291
    2-s2.0-85163665052
    2-s2.0-85163662192
    2-s2.0-85163638571
    2-s2.0-85163600275
    2-s2.0-85163599662
    2-s2.0-85163593848
    2-s2.0-85163583048
    2-s2.0-85163406865
    2-s2.0-85163402538
    2-s2.0-85163383612
    2-s2.0-85163380553
    2-s2.0-85163377017
    2-s2.0-85163373309
    2-s2.0-85163368962
    2-s2.0-85163361046
    2-s2.0-85163357787
    2-s2.0-85163356021
    2-s2.0-85163353194
    2-s2.0-85163350617
    2-s2.0-85163350459
    2-s2.0-85163350363
    2-s2.0-85163345088
    2-s2.0-85163342186
    2-s2.0-85163339322
    2-s2.0-85163335297
    2-s2.0-85163324921
    2-s2.0-85163324330
    2-s2.0-85163323603
    2-s2.0-85163322268
    2-s2.0-85163315735
    2-s2.0-85163314125
    2-s2.0-85163313188
    2-s2.0-85163299881
    2-s2.0-85163299229
    2-s2.0-85163284828
    2-s2.0-85163284425
    2-s2.0-85163276908
    2-s2.0-85163042309
    2-s2.0-85163017440
    2-s2.0-85163008133
    2-s2.0-85163001614
    2-s2.0-85162993960
    2-s2.0-85162176776
    2-s2.0-85162037594
    2-s2.0-85161720786
    2-s2.0-85161718196
    2-s2.0-85161715575
    2-s2.0-85161701735
    2-s2.0-85161698310
    2-s2.0-85161695948
    2-s2.0-85161677371
    2-s2.0-85161676728
    2-s2.0-85161665556
    2-s2.0-85161654678
    2-s2.0-85161654117
    2-s2.0-85161649403
    2-s2.0-85161648116
    2-s2.0-85161642524
    2-s2.0-85161637705
    2-s2.0-85161627472
    2-s2.0-85161627313
    2-s2.0-85161625568
    2-s2.0-85161623356
    2-s2.0-85161496756
    2-s2.0-85161440036
    2-s2.0-85161428089
    2-s2.0-85161413910
    2-s2.0-85161409126
    2-s2.0-85161397981
    2-s2.0-85161391475
    2-s2.0-85161386409
    2-s2.0-85161378935
    2-s2.0-85161378470
    2-s2.0-85161377586
    2-s2.0-85161372554
    2-s2.0-85161368601
    2-s2.0-85161359142
    2-s2.0-85161336518
    2-s2.0-85161311453
    2-s2.0-85161303282
    2-s2.0-85161302808
    2-s2.0-85161295115
    2-s2.0-85161284366
    2-s2.0-85161255503
    2-s2.0-85161254080
    2-s2.0-85161252498
    2-s2.0-85161242474
    2-s2.0-85161239784
    2-s2.0-85161235182
    2-s2.0-85161232886
    2-s2.0-85161232378
    2-s2.0-85161231369
    2-s2.0-85161219491
    2-s2.0-85161187369
    2-s2.0-85161182996
    2-s2.0-85161182265
    2-s2.0-85161178482
    2-s2.0-85161178410
    2-s2.0-85161175472
    2-s2.0-85161173544
    2-s2.0-85161173376
    2-s2.0-85161171261
    2-s2.0-85161170091
    2-s2.0-85161151204
    2-s2.0-85161146673
    2-s2.0-85161132057
    2-s2.0-85161118232
    2-s2.0-85161116339
    2-s2.0-85161114857
    2-s2.0-85161113839
    2-s2.0-85161110870
    2-s2.0-85161110057
    2-s2.0-85161107868
    2-s2.0-85161103855
    2-s2.0-85160866077
    2-s2.0-85160579391
    2-s2.0-85160558580
    2-s2.0-85160531525
    2-s2.0-85160526071
    2-s2.0-85160514067
    2-s2.0-85160513250
    2-s2.0-85160510913
    2-s2.0-85160443863
    2-s2.0-85160438608
    2-s2.0-85160436152
    2-s2.0-85160412414
    2-s2.0-85160408223
    2-s2.0-85160403637
    2-s2.0-85159497661
    2-s2.0-85159485365
    2-s2.0-85159484162
    2-s2.0-85159478949
    2-s2.0-85159476693
    2-s2.0-85159467158
    2-s2.0-85159458641
    2-s2.0-85159454509
    2-s2.0-85159450518
    2-s2.0-85159449500
    2-s2.0-85159449305
    2-s2.0-85159446480
    2-s2.0-85159443829
    2-s2.0-85159411824
    2-s2.0-85159408773
    2-s2.0-85159402772
    2-s2.0-85159402017
    2-s2.0-85159400138
    2-s2.0-85159399946
    2-s2.0-85159399736
    2-s2.0-85159387777
    2-s2.0-85159113740
    2-s2.0-85158965423
    2-s2.0-85156182428
    2-s2.0-85156180306
    2-s2.0-85156175595
    2-s2.0-85156153930
    2-s2.0-85156150995
    2-s2.0-85156146907
    2-s2.0-85156146236
    2-s2.0-85156136052
    2-s2.0-85156125787
    2-s2.0-85156119227
    2-s2.0-85156117682
    2-s2.0-85153881772
    2-s2.0-85153873248
    2-s2.0-85153865580
    2-s2.0-85153860974
    2-s2.0-85153846275
    2-s2.0-85152978927
    2-s2.0-85152589300
    2-s2.0-85152586505
    2-s2.0-85152581880
    2-s2.0-85152578853
    2-s2.0-85152578512
    2-s2.0-85152577334
    2-s2.0-85152573690
    2-s2.0-85152571633
    2-s2.0-85152563758
    2-s2.0-85152558687
    2-s2.0-85152550942
    2-s2.0-85152548893
    2-s2.0-85152546353
    2-s2.0-85152539153
    2-s2.0-85152527767
    2-s2.0-85152526853
    2-s2.0-85152524855
    2-s2.0-85152522856
    2-s2.0-85152518610
    2-s2.0-85152517635
    2-s2.0-85152515611
    2-s2.0-85152472480
    2-s2.0-85152440782
    2-s2.0-85152413687
    2-s2.0-85152404114
    2-s2.0-85152389627
    2-s2.0-85152367474
    2-s2.0-85151164859
    2-s2.0-85151164610
    2-s2.0-85151160554
    2-s2.0-85151160421
    2-s2.0-85151155274
    2-s2.0-85151154756
    2-s2.0-85151152513
    2-s2.0-85151152429
    2-s2.0-85151151627
    2-s2.0-85151150431
    2-s2.0-85151150294
    2-s2.0-85151146171
    2-s2.0-85151145495
    2-s2.0-85151144827
    2-s2.0-85151138527
    2-s2.0-85151138172
    2-s2.0-85151136923
    2-s2.0-85151136393
    2-s2.0-85151135465
    2-s2.0-85151130820
    2-s2.0-85151130679
    2-s2.0-85151129937
    2-s2.0-85151129510
    2-s2.0-85151126962
    2-s2.0-85151124473
    2-s2.0-85151123618
    2-s2.0-85151123481
    2-s2.0-85151123466
    2-s2.0-85151122977
    2-s2.0-85151121323
    2-s2.0-85151120634
    2-s2.0-85151052379
    2-s2.0-85150973281
    2-s2.0-85149997675
    2-s2.0-85149969133
    2-s2.0-85149899528
    2-s2.0-85149893608
    2-s2.0-85149891234
    2-s2.0-85149890498
    2-s2.0-85149887526
    2-s2.0-85149886439
    2-s2.0-85149886286
    2-s2.0-85149881748
    2-s2.0-85149868409
    2-s2.0-85149867931
    2-s2.0-85149867517
    2-s2.0-85149861121
    2-s2.0-85149859174
    2-s2.0-85149841173
    2-s2.0-85149827587
    2-s2.0-85149818641
    2-s2.0-85149812761
    2-s2.0-85149811983
    2-s2.0-85149703444
    2-s2.0-85149703113
    2-s2.0-85149695782
    2-s2.0-85149692874
    2-s2.0-85149692031
    2-s2.0-85149691440
    2-s2.0-85149690653
    2-s2.0-85149681838
    2-s2.0-85149679186
    2-s2.0-85149678827
    2-s2.0-85149675715
    2-s2.0-85149671190
    2-s2.0-85149669632
    2-s2.0-85149665198
    2-s2.0-85149659638
    2-s2.0-85149649742
    2-s2.0-85149648949
    2-s2.0-85149641221
    2-s2.0-85149631493
    2-s2.0-85149631172
    2-s2.0-85149631095
    2-s2.0-85149629868
    2-s2.0-85149622640
    2-s2.0-85149619219
    2-s2.0-85149480346
    2-s2.0-85149469603
    2-s2.0-85149464520
    2-s2.0-85149456671
    2-s2.0-85149455760
    2-s2.0-85149447949
    2-s2.0-85148698141
    2-s2.0-85148695290
    2-s2.0-85148241581
    2-s2.0-85148217236
    2-s2.0-85148215133
    2-s2.0-85148214952
    2-s2.0-85148213347
    2-s2.0-85148212835
    2-s2.0-85148102809
    2-s2.0-85148068139
    2-s2.0-85148062356
    2-s2.0-85148058744
    2-s2.0-85148048389
    2-s2.0-85148047047
    2-s2.0-85148041937
    2-s2.0-85148041010
    2-s2.0-85148039551
    2-s2.0-85148035316
    2-s2.0-85148031132
    2-s2.0-85148023111
    2-s2.0-85148022466
    2-s2.0-85148019682
    2-s2.0-85148017557
    2-s2.0-85148017089
    2-s2.0-85148016670
    2-s2.0-85148013199
    2-s2.0-85148012723
    2-s2.0-85148009735
    2-s2.0-85148006538
    2-s2.0-85148006251
    2-s2.0-85148001774
    2-s2.0-85148001478
    2-s2.0-85148000670
    2-s2.0-85147999541
    2-s2.0-85147997311
    2-s2.0-85147996720
    2-s2.0-85147996619
    2-s2.0-85147996371
    2-s2.0-85147995619
    2-s2.0-85147993880
    2-s2.0-85147993598
    2-s2.0-85147992045
    2-s2.0-85147989873
    2-s2.0-85147988956
    2-s2.0-85147988445
    2-s2.0-85147987966
    2-s2.0-85147986142
    2-s2.0-85147985973
    2-s2.0-85147984937
    2-s2.0-85147983818
    2-s2.0-85147878371
    2-s2.0-85147876808
    2-s2.0-85147874107
    2-s2.0-85147873256
    2-s2.0-85147872725
    2-s2.0-85147866326
    2-s2.0-85147863118
    2-s2.0-85147858060
    2-s2.0-85147856699
    2-s2.0-85147854817
    2-s2.0-85147851268
    2-s2.0-85147850794
    2-s2.0-85147849303
    2-s2.0-85147848647
    2-s2.0-85147846988
    2-s2.0-85147846263
    2-s2.0-85147841102
    2-s2.0-85147840963
    2-s2.0-85147447032
    2-s2.0-85147429004
    2-s2.0-85146724305
    2-s2.0-85146708747
    2-s2.0-85146705181
    2-s2.0-85146705050
    2-s2.0-85146701480
    2-s2.0-85146700876
    2-s2.0-85146694011
    2-s2.0-85146693893
    2-s2.0-85146692662
    2-s2.0-85146685642
    2-s2.0-85146682600
    2-s2.0-85146670131
    2-s2.0-85146665376
    2-s2.0-85146664118
    2-s2.0-85146658232
    2-s2.0-85146655815
    2-s2.0-85146653447
    2-s2.0-85146648703
    2-s2.0-85146648445
    2-s2.0-85146648352
    2-s2.0-85146647840
    2-s2.0-85146644305
    2-s2.0-85146639933
    2-s2.0-85146637491
    2-s2.0-85146255535
    2-s2.0-85146252874
    2-s2.0-85146250254
    2-s2.0-85146249289
    2-s2.0-85146246523
    2-s2.0-85146238308
    2-s2.0-85146237813
    2-s2.0-85146236752
    2-s2.0-85146233869
    2-s2.0-85146228060
    2-s2.0-85146224748
    2-s2.0-85146221612
    2-s2.0-85146217916
    2-s2.0-85146214807
    2-s2.0-85145238826
    2-s2.0-85145220040
    2-s2.0-85145169560
    2-s2.0-85145162346
    2-s2.0-85145105499
    2-s2.0-85145085853
    2-s2.0-85145066967
    2-s2.0-85145021958
    2-s2.0-85145021645
    2-s2.0-85145021442
    2-s2.0-85145021174
    2-s2.0-85145020802
    2-s2.0-85145020429
    2-s2.0-85145020086
    2-s2.0-85145019843
    2-s2.0-85145019784
    2-s2.0-85145019719
    2-s2.0-85145019455
    2-s2.0-85145018865
    2-s2.0-85145018691
    2-s2.0-85145018433
    2-s2.0-85145018170
    2-s2.0-85144628937
    2-s2.0-85144626357
    2-s2.0-85144624032
    2-s2.0-85144599234
    2-s2.0-85144592415
    2-s2.0-85137833659
    2-s2.0-85120911476
    2-s2.0-85126278511
    2-s2.0-85174988226
    2-s2.0-85174986490
    2-s2.0-85162068496
    2-s2.0-85162057601
    2-s2.0-85162009216
    2-s2.0-85161997647
    2-s2.0-85161996073
    2-s2.0-85161965066
    2-s2.0-85160343444
    2-s2.0-85160300859
    2-s2.0-85160297267
    2-s2.0-85160294956
    2-s2.0-85160279435
    2-s2.0-85153119306
    2-s2.0-85153073686
    2-s2.0-85153053434
    2-s2.0-85153041683
    2-s2.0-85152886475
    2-s2.0-85152465552
    2-s2.0-85151548459
    2-s2.0-85148700167
    2-s2.0-85148698546
    2-s2.0-85148697882
    2-s2.0-85148697240
    2-s2.0-85148695326
    2-s2.0-85148694564
    2-s2.0-85148691478
    2-s2.0-85148689968
    2-s2.0-85148688912
    2-s2.0-85148683922
    2-s2.0-85148683587
    2-s2.0-85148037460
    2-s2.0-85148033139
    2-s2.0-85148000557
    2-s2.0-85147857889
    2-s2.0-85147856604
    2-s2.0-85147851726
    2-s2.0-85147850799
    2-s2.0-85147850663
    2-s2.0-85147849129
    2-s2.0-85147841998
    2-s2.0-85146713349
    2-s2.0-85146687031
    2-s2.0-85146686383
    2-s2.0-85146685100
    2-s2.0-85146668366
    2-s2.0-85146641823
    2-s2.0-85146638736
    2-s2.0-85146567261
    2-s2.0-85146562488
    2-s2.0-85146544035
    2-s2.0-85146240403
    2-s2.0-85145441676
    2-s2.0-85145439843
    2-s2.0-85145438363
    2-s2.0-85145435227
    2-s2.0-85145433046
    2-s2.0-85145432963
    2-s2.0-85145265724
    2-s2.0-85145265443
    2-s2.0-85145264880
    2-s2.0-85145264696
    2-s2.0-85145264515
    2-s2.0-85145263551
    2-s2.0-85145261713
    2-s2.0-85145260618
    2-s2.0-85145260048
    2-s2.0-85145259569
    2-s2.0-85145258445
    2-s2.0-85145258062
    2-s2.0-85145256181
    2-s2.0-85145254964
    2-s2.0-85145254936
    2-s2.0-85145253991
    2-s2.0-85145253878
    2-s2.0-85145253825
    2-s2.0-85145252989
    2-s2.0-85145252361
    2-s2.0-85145251376
    2-s2.0-85145251219
    2-s2.0-85145240276
    2-s2.0-85145212525
    2-s2.0-85145211465
    2-s2.0-85145206016
    2-s2.0-85145193243
    2-s2.0-85145188859
    2-s2.0-85145187895
    2-s2.0-85145184206
    2-s2.0-85145181319
    2-s2.0-85145179452
    2-s2.0-85145173374
    2-s2.0-85145169671
    2-s2.0-85145021980
    2-s2.0-85145021561
    2-s2.0-85145021199
    2-s2.0-85145020673
    2-s2.0-85145020024
    2-s2.0-85145019748
    2-s2.0-85145019014
    2-s2.0-85145018718
    2-s2.0-85145017888
    2-s2.0-85144827383
    2-s2.0-85144824075
    2-s2.0-85144821716
    2-s2.0-85144818442
    2-s2.0-85144817733
    2-s2.0-85144633980
    2-s2.0-85144633347
    2-s2.0-85144633194
    2-s2.0-85144632600
    2-s2.0-85144631831
    2-s2.0-85144631246
    2-s2.0-85144630191
    2-s2.0-85144629882
    2-s2.0-85144629867
    2-s2.0-85144629836
    2-s2.0-85144627009
    2-s2.0-85144623085
    2-s2.0-85144620103
    2-s2.0-85144619873
    2-s2.0-85144619771
    2-s2.0-85144617159
    2-s2.0-85144615620
    2-s2.0-85144615341
    2-s2.0-85144614979
    2-s2.0-85144612556
    2-s2.0-85144609555
    2-s2.0-85144606163
    2-s2.0-85144605792
    2-s2.0-85144601872
    2-s2.0-85144601352
    2-s2.0-85144600720
    2-s2.0-85144600010
    2-s2.0-85144599690
    2-s2.0-85144599640

In [6]:
import os
print(os.path.abspath(os.getcwd()))

df = pd.DataFrame(acc, columns=["Paper title", "Paper eid", "Paper doi", "Citing paper title", "Citing paper eid", "Citing paper doi"])
df.to_csv("/home/data/scopus-citations-{}.csv".format(time.time()), index=False)
df

/

,Paper title,Paper eid,Paper doi,Citing paper title,Citing paper eid,Citing paper doi
0,Process-driven design of cloud data platforms,2-s2.0-85216873928,10.1016/j.is.2025.102527,,,
1,Automating materiality assessment with a data-...,2-s2.0-85213286497,10.1016/j.jjimei.2024.100310,,,
2,An auto-tuning process-based 3D model to forec...,2-s2.0-85212101165,10.1016/j.ecoinf.2024.102947,,,
3,VOOL: A modular insight-based framework for vo...,2-s2.0-85211035819,10.1016/j.is.2024.102496,,,
4,Colossal Trajectory Mining: A unifying approac...,2-s2.0-85174707802,10.1016/j.eswa.2023.122055,Particle filtering supported probability densi...,2-s2.0-85190319631,10.1016/j.heliyon.2024.e29437
...,...,...,...,...,...,...
1146,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Modelling and simulation of Opportunistic IoT ...,2-s2.0-85053778744,10.1016/j.future.2018.09.005
1147,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,The share operator for field-based coordination,2-s2.0-85067426015,10.1007/978-3-030-22397-7_4
1148,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,From field-based coordination to aggregate com...,2-s2.0-85048884985,10.1007/978-3-319-92408-3_12
1149,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Practical Aggregate Programming with Protelis,2-s2.0-85035242264,10.1109/FAS-W.2017.186
1150,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Self-Stabilising Target Counting in Wireless S...,2-s2.0-85035210635,10.1109/SASO.2017.10

In [7]:
import numpy as np
df = df.replace("", np.nan)
df["Citing paper title"].isna()

0        True
1        True
2        True
3        True
4       False
        ...
1146    False
1147    False
1148    False
1149    False
1150    False
Name: Citing paper title, Length: 1151, dtype: bool

Total citations

In [8]:
s = df.groupby(["Paper title"])["Citing paper title"].count()
s.sum()

np.int64(1137)

Citation details

In [9]:
s.sort_values(ascending=False).to_csv("/home/data/scopus-summary-{}.csv".format(time.time()))